slskd/slskd

src/slskd/Program.cs, src/slskd/Startup.cs, src/slskd/slskd.csproj
Adds:
* The Prometheus metrics server (prometheus-net)
* ASP.NET Core metrics (kestrel and request) (prometheus-net.AspNetCore)
* ASP.NET health checks (to be implemented in #17) (prometheus-net.AspNetCore.HealthChecks)
* .NET Runtime metrics (prometheus-net.DotNetRuntime)
* Basic system metrics (CPU, memory, network, disk) (prometheus-net.SystemMetrics)
Custom metrics for internals of the Soulseek library and slskd are TBD.
Metrics (in Prometheus format) are available at `/metrics`
=> Add Prometheus metrics

src/slskd/Program.cs
```Unable to configure HTTPS endpoint. No server certificate was specified, and the default developer certificate could not be found or is out of date.```
I thought this seemed a little too easy.  I'll need to put this off until I can add certificate handling.
=> Temporarily disable HTTPS

src/slskd/Program.cs, src/slskd/Startup.cs, src/slskd/slskd.csproj
`slskd.yml` configuration is now stored in `/config`, `slskd.xml` is now stored in `/etc`, and the SQLite database will eventually be stored in `/data`.
This PR also ensures that logs are stored relative to the app executable, rather than to the project root.
=> Move XML documentation and configuration to subdirectories

.github/workflows/ci.yml, Dockerfile
The Dockerfile now uses Ubuntu images for the build, publish and runtime stages due to various incompatibilities with Alpine.  This nearly triples the size of the resulting image (from ~20mb to ~60mb), but reduces friction and adds support for the most likely usage scenarios.
The build artifacts for `linux-musl-*` have been removed from the build output because of this move away from Alpine.
=> Add ARM/v7 and ARM64 to Docker image

src/slskd/Service.cs
Fixes a regression from the Soulseek.NET example app: https://github.com/jpdillingham/Soulseek.NET/issues/493
=> Use local username when sending search results

src/slskd/Service.cs
This allows other users to see our average speed, and for the server to determine our role in the distributed network.
=> Send speed of completed uploads to the server 

src/slskd/API/Controllers/TransfersController.cs, src/slskd/Common/Extensions.cs, src/slskd/Options.cs, src/slskd/Program.cs, src/slskd/Properties/analysis.ruleset, src/slskd/Properties/slskd.yml, src/slskd/Service.cs, src/slskd/Startup.cs, src/slskd/Trackers/TransferTracker.cs
This PR stores incomplete downloads in a separate (configurable) directory from completed downloads, and moves them from the incomplete directory to the complete directory upon completion.
It didn't seem reasonable to force users to specify a directory for incomplete downloads, so I added options for both "app" and "incomplete" directories, with "app" being a general directory for application data.
The "app" directory defaults to `%localappdata%\slskd` on Windows systems and `~/.local/share/slskd` on Linux-like systems.
The "incomplete", "downloads", and "shared" directories are no longer required options, and if omitted they will default to `<app>\<incomplete|downloads|shared>`, respecting whatever the "app" directory has been configured to.  Each of these three directories can still be …
=> Save incomplete downloads in a separate directory

src/slskd/Common/Validation/DirectoryExistsAttributes.cs
This was causing a failure to start when the default directories were not yet present.  This PR bypasses the validation for any directories that fall within the default app directory, as it is presumed that the app can read/write to this directory.
=> Don't invalidate missing directories if they are within the default path

src/web/src/components/Search/Search.css, src/web/src/components/Search/Search.js, src/web/src/components/Users/Users.js, src/web/src/lib/search.js, src/web/src/lib/search.test.js
Adds an input box beneath the existing filtering and sorting options for search results.  The filters match the functionality of the official client.
Closes #85
=> Add search result filter

src/slskd/Core/Common/Exceptions/ApplicationShutdownException.cs, src/slskd/Core/Common/Exceptions/SlskdException.cs, src/slskd/Core/Service.cs
Also establishes the `SlskdException` base class for exceptions thrown from slskd logic.
=> Don't try to reconnect following an intentional shutdown

Dockerfile
Debian doesn't have a tool for making HTTP requests installed out of the box, so we need to add `wget` via apt when we build the image.
Closes #99
=> Fix container health check

src/slskd/Application/Service.cs, src/slskd/Integrations/Pushbullet/IPushbulletService.cs, src/slskd/Integrations/Pushbullet/PushbulletService.cs, src/slskd/Options.cs, src/slskd/Properties/analysis.ruleset, src/slskd/Properties/slskd.yml, src/slskd/Startup.cs
Adds the following configuration options (shown as they would appear in the yaml config):
```yaml
pushbullet:
enabled: false                    # enable/disable
access_token: ~                   # Pushbullet API token (from your account details)
notification_prefix: From slskd:  # prefix for pushes
notify_on_private_message: true   # push on private message
notify_on_room_mention: true      # push on room mention
retry_attempts: 3                 # number of times to retry failed pushes (exponential backoff)
cooldown_time: 900000             # minimum time between similar pushes (15 minutes)
```
When enabled, push notifications will be sent to Pushbullet for private messages and public chat room mentions of the currently logged in username.  Notifications are keyed on the username of the …
=> Add Pushbullet integration for private messages and room mentions

Dockerfile
This PR sets the environment variable `DOTNET_BUNDLE_EXTRACT_BASE_DIR` to `/var/tmp/.net`, which matches the behavior prior to .NET 5, and works around the issue of `$HOME`-less users.
Through testing I discovered a previous change to make the creation of internal directories less verbose wasn't working (because it relied on `bash` expansion, and I wasn't using bash), so that's fixed, and I added a command to `chmod 777` the internal directories so that users other than root can r/w/x them.
I tested with:
```
docker run -it \
-u $(id -u):$(id -g) \
-p 5000:5000 \
-p 5001:5001 \
-v ~/Downloads:/var/slskd/downloads \
-v ~/Shared:/var/slskd/shared \
-e "SLSKD_SLSK_USERNAME=<redacted>" \
-e "SLSKD_SLSK_PASSWORD=<redacted>" \
--name slskd \
slskd/slskd:latest
```
And confirmed that downloaded …
=> Make Dockerfile more friendly to non-root users

README.md
Hi, I noticed that passing incoming directory is required by configuration:
```
$ docker run -d \
-p 5000:5000 \
-p 5001:5001 \
-v <redacted>:/var/slskd/downloads \
-v <redacted>:/var/slskd/shared \
-e "SLSKD_SLSK_USERNAME=<redacted>" \
-e "SLSKD_SLSK_PASSWORD=<redacted>" \
--name slskd \
slskd/slskd:latest
$ docker logs slskd
Invalid configuration:
Directories:
The Incomplete field specifies a non-existent directory '/var/slskd/incomplete'.
```
=> 📝 Updated Quick Start example

src/slskd/Options.cs, src/slskd/Program.cs
Sometimes I want to run the application to test out initialization code.  Currently I have to kill the app manually, and usually after it has connected to the server and begun the process of finding a distributed parent.
This PR adds command-line and environment variable options to force the application to quit after initialization logic has been executed, and before startup.
=> Add 'no-start' option

src/slskd/Application/Service.cs
I believe the `File not found.` transfer status message is an oversight, since the Soulseek.NET library and official clients deal with `File not shared.` messages.
=> Rename 'File not found.' message to 'File not shared.'

src/slskd/Application/Service.cs, src/slskd/Common/Configuration/CommandLineConfigurationSource.cs, src/slskd/Common/Configuration/DefaultValueConfigurationSource.cs, src/slskd/Common/Configuration/EnvironmentVariableConfigurationSource.cs, src/slskd/Common/Extensions.cs, src/slskd/Options.cs, src/slskd/Program.cs, src/slskd/slskd.csproj
Allows types `string[]` and `int[]` to be used as backing types for `Option` properties.  When these types are used, environment variables can be specified as strings with multiple values delimited by semicolons (e.g. `"foo;bar;baz"` is expanded to `[ 'foo', 'bar', 'baz' ]`.  Command line arguments backed by array types can be specified multiple times (e.g. `--foo bar --foo baz` is expanded to `[ 'bar', 'baz' ]`.
Multiple values are represented in YAML in the standard way.
Closes #124 
Closes #129
=> Accept option lists via command line and environment variables

src/slskd/Application/Application.cs, src/slskd/Application/ApplicationState.cs, src/slskd/Application/ISharedFileCache.cs, src/slskd/Application/SharedFileCache.cs, src/slskd/Common/Compute.cs, src/slskd/Common/Extensions.cs, src/slskd/Properties/analysis.ruleset
This PR adds functionality to the shared file cache to mask all but the most immediate directory in shared directories.  
The path:
```/home/Foo/My Sensitive Filepath/Music/Shared```
Appears in browse and search results as:
```@@hash/Shared```
The hash is computed by first computing the SHA1 hash of the directory, then by converting the hash to base 64, removing numbers, converting all letters to lowercase, and then taking the first 5.
I'm pretty sure at this point that Soulseek (Qt at least) is expecting hashes that:
* Begin with `@@`
* Contain only lowercase letters (no numbers)
* Are exactly 7 characters in length (including `@@` and 5 additional characters)
Including numbers seems to only obscure the path up to the first number, and including uppercase characters seems to invalidate …
=> Substitute share paths with a hash

src/slskd/Application/SharedFileCache.cs, src/slskd/Application/SharedFileCacheState.cs
Shared directories prefixed with either `-` or `!` are treated as exclusions, and those directories and any child directories are not returned in browse or search results.
Closes #54
=> Add the ability to exclude directories from sharing

src/slskd/Application/Exceptions/ShareAliasException.cs, src/slskd/Application/SharedFileCache.cs, src/slskd/Options.cs, src/slskd/Program.cs
This PR adds the ability to alias shared directories, giving users greater control over how their files show up to other users without requiring the physical location of files to be changed.
Closes #150
=> Add share aliases

src/slskd/Program.cs
Creating the default shared directory suppresses the error reported in #155
=> Create default shared directory on startup

src/slskd/Application/SharedFileCache.cs, src/slskd/Options.cs, src/slskd/Program.cs
The inability to override the default share is causing users issues and the use case is hypothetical.  This PR removes it.
=> Default shares to an empty array.  Warn if no shares are configured

src/slskd/Application/SharedFileCache.cs
The shared file cache uses the SQLite FTS5 extension for full-text searching, but when I implemented it I didn't spend a lot of time reading through the docs to see how to get the best matching.
This PR improves matching by allowing search tokens to be located anywhere in a string, rather than strictly ordered according to the query, and includes any terms specified in the query as exclusions (prefixed with -)
Partially addresses #158
=> Improve search matching

src/slskd/Application/SharedFileCache.cs, src/slskd/Program.cs
The general guidance is to avoid cross-thread access of SQLite connections, and the best way to do that, without getting into some esoteric connection pooling scheme, is to create a new one for each query.
I profiled the memory usage with this change for ~12 hours and confirmed that it doesn't cause any leaks or undue GC pressure, and queries themselves generally come back in 0-2ms either way, so I don't anticipate any performance issues.
Closes #178
Closes #179
=> Use a new SQLite connection for each search request

src/slskd/Application/Application.cs, src/slskd/Options.cs, src/slskd/slskd.csproj
A configured list of chat rooms will now be automatically joined on connect.
The list can be specified via command line (e.g. `--rooms <room1> --rooms <room2>`), with the `SLSKD_ROOMS` environment variable (rooms separated by a semicolon), or in the yaml file as follows:
```yaml
rooms:
- <room 1>
- <room 2>
```
Additionally, when the client is disconnected, any rooms that were joined at the time of the disconnect are rejoined upon reconnect, as long as the app hasn't been restarted in between.
Closes #92
=> Add the ability to automatically join rooms on login

src/slskd/Application/SharedFileCache.cs, src/slskd/Options.cs
Built in functions for working with paths hide a lot of ambiguous behavior and are a general pain to work with.  In this case, when using `GetParent()` to get the parent of a given directory, a string _not_ ending with a trailing slash is returned, _except_ when that path is a root:
```c#
Console.WriteLine(Directory.GetParent(@"C:\foo\bar"));
Console.WriteLine(Directory.GetParent(@"C:\foo"));
```
```
C:\foo
C:\
```
This PR adds some additional code to remove the trailing slash after using `GetParent()`.
There's also some very strange behavior when working with root paths, so those are explicitly forbidden when validating the configuration.
Addresses #200
=> Fix share path issues when the parent directory is a root

src/slskd/slskd.csproj
The server garbage collection mode seems to perform poorly and use more overhead than the workstation mode.  I must have tested and concluded this a while ago, but it's good to test again since the framework has changed quite a bit since then.
I'm guessing the tendency of the application to create massive amounts of new objects during searches and then immediately discard them is the root of the problem, that's more consistent with a workstation type of workload than a server (I guess?).
It may be worthwhile revisiting this once things are migrated to .NET 6.
=> Use workstation garbage collection

src/slskd/Application.cs
Noticed this while viewing the user info of a slskd user. Since the picture is not null, the HasPicture parameter in the user info response message is set to true: https://github.com/jpdillingham/Soulseek.NET/blob/8f5e6582aee1dc17b473a11b5b9e056abdc9564e/src/UserInfo.cs#L36
=> Don't send empty picture in user info response

src/web/src/components/Transfers/TransferGroup.js
Clicking retry on failed download(s) does not seem to work at all for me. To reproduce:
1. Search for something to download.
2. Switch to downloads tab and watch it start.
3. Force it to fail somehow.
4. Progress says "Completed, Errored" and the progress bar is 100% red.
5. Select the failed download(s) using the checkbox and press the green retry button at bottom of the page.
This error is being logged in the browser console.
```
Uncaught (in promise) TypeError: e.map is not a function
retryAll TransferGroup.js:54
onClick TransferGroup.js:123
Lodash 4
handleClick Button.js:63
React 12
unstable_runWithPriority scheduler.production.min.js:19
React 3
```
Looking at it TransferGroup->retryAll function is expecting 1 parameter but it is being called with 3. Only the 3rd parameter should be …
=> Retry button on failed downloads fails with a script error

bin/publish
There are a bunch of problems with trimmed libraries and .NET 6 that are causing runtime errors.  This PR disables trimming.
Unless there's a clear performance benefit to staying on .NET 6, I'll revert to .NET 5.
=> Don't trim while publishing

bin/publish, src/slskd/slskd.csproj
Changes in .NET 6 broke some aspects of trimming.  This should fix them.
I followed the guidance from: https://docs.microsoft.com/en-us/dotnet/core/deploying/trimming/trimming-options
=> Adjust release trimming options

config/slskd.example.yml, src/slskd/Application.cs, src/slskd/Options.cs
Transfer speeds are sensitive to the buffer size used, which ends up being much larger than the buffer needed for other types of communication.  This PR separates the two.
Specify the transfer buffer option with:
* `--slsk-transfer-buffer` on the command line
* The `SLSKD_SLSK_TRANSFER_BUFFER` environment variable
* The `transfer` property in the yaml, under `soulseek.connection.buffer`.
The value defaults to `262144` (256 kib) and can't be set any lower than `81920` (80 kib).  
Rationale for the lower limit can be found here: https://github.com/dotnet/runtime/blob/main/src/libraries/System.Private.CoreLib/src/System/IO/Stream.cs#L122-L127 (internally, transfers are a copy of data from stream to stream.  I could be convinced that this isn't the same thing since there's a socket in …
=> Add transfer buffer option

src/slskd/Application.cs, src/slskd/Common/Configuration/YamlConfigurationSource.cs
The new .NET serializer is not very forgiving, and throws on some values that are being logged when patching configuration options.  This PR removes the logging of the serialized option patch.
Also fixes a bug in socket configuration and yaml processing.
=> Fix bug causing failed option update

src/slskd/Common/Cryptography/Random.cs, src/slskd/Common/Extensions.cs, src/slskd/Options.cs, src/slskd/Program.cs
A couple of things were generating Guids to use as secrets, which are pretty random but also not very.  This PR generates an RNG byte array and then converts it to a base 62 string instead.
Closes #286 
Closes #289
=> Use more secure strings for secrets

src/slskd/Shares/SharedFileCache.cs
The code previously replaced single quotes with two single quotes to escape them prior to inserting them into the SQLite cache, which worked but caused strings with two single quotes (e.g. 12'') to be erroneously substituted on the way out, causing errors matching results to `File` records.
This PR changes the insert to use a parameter, so no escaping is needed.
For posterity, I did try to use parameters with the query used to find matching, and it appears as though the `MATCH` clause doesn't accept them so escaping will remain there.
Closes #269
=> Don't escape single quotes when scanning shares

src/web/src/components/Browse/Directory.js, src/web/src/components/Transfers/TransferGroup.js, src/web/src/components/Transfers/TransferList.js
Previously, buttons for uploads and downloads weren't treated differently, and they should have been.  Clicking the button of an upload would cause the code to attempt to download that file from the requesting user.
This PR prevents the buttons associated with uploads from doing anything when clicked (as there is nothing that can be done, other than cancel, and there's already a mechanism for that), and tweaks the UI to make them appear more like status indicators rather than buttons (removes cursor, removes mouseover effects)
Closes #260
Closes #306
=> Upload identity

src/slskd/Search/API/Hubs/SearchHub.cs, src/slskd/Search/SearchService.cs, src/slskd/Startup.cs
This was added to facilitate some testing of real-time updates on the UI, but halfway through I realized that pretty much everything around searches needs to be refactored.  This hub is likely to be used in the future, so I'm committing it to avoid the rework.
=> Add Search SignalR hub

src/slskd/Application.cs, src/slskd/Common/Extensions.cs, src/slskd/Transfers/API/Controllers/TransfersController.cs, src/slskd/slskd.csproj
Note that there's a new option in Soulseek.NET, `MaximumConcurrentUploads`, which defaults to 10 and for which there is no option in slskd, so the canary that is built from this merge commit will be stuck at 10.
I'll have a fast-follow PR to add the option to slskd settings.
=> Bump dependencies, including Soulseek.NET to 4.0.0

config/slskd.example.yml, src/slskd/Application.cs, src/slskd/Common/Configuration/YamlConfigurationSource.cs, src/slskd/Common/Extensions.cs, src/slskd/Common/QueueStrategy.cs, src/slskd/Common/Validation/ValidateAttribute.cs, src/slskd/Options.cs, src/slskd/Startup.cs
Related to #127, but there's still a bunch of additional work to do.
I started to add individual queues and user lists in this PR but I need to spend more time on it, and this part was ready now.  I'm leaving some of the stuff that was added for queue config in, and will follow up soon.
I'm not going to update the configuration docs just yet because I'm not sure I am happy with where this is implemented, but for the time being it can be set in the yaml with:
```yaml
limits:
queue:
slots: 10
```
Via the command line with `--queue-slot-limit` or environment variable with `SLSKD_QUEUE_SLOT_LIMIT`
=> Add option to set a limit for total number of upload slots

src/slskd/slskd.csproj
Fixes a critical bug limiting downloads to one at a time.
=> Bump Soulseek.NET to 4.4.2

bin/cover, tests/slskd.Tests.Integration/slskd.Tests.Integration.csproj, tests/slskd.Tests.Unit/slskd.Tests.Unit.csproj
To generate and display code coverage in VS Code, install ".NET Test Explorer" and "Coverage Gutters" extensions, and add the following to settings:
```
"dotnet-test-explorer.testArguments": "/p:CollectCoverage=true /p:CoverletOutputFormat=lcov /p:CoverletOutput=TestResults/lcov.info",
"coverage-gutters.coverageReportFileName": "tests/**/TestResults/lcov.info",
```
=> Add tools to generate code coverage

Dockerfile
Testing whether removing this instruction makes any difference in Unraid.  Because ports are user-configurable, it maybe doesn't make sense to expose them, anyway, as the exposed ports won't change according to the configuration and can cause confusion.
Related to #365
=> Remove EXPOSE instruction from Dockerfile

src/web/src/lib/api.js, src/web/src/lib/hubFactory.js
Enables operation behind a reverse proxy implementing basic auth.  It should work for other schemes like cookies also.
Closes #339
=> Pass credentials to signalr hub negotiation when auth is disabled

Dockerfile
When running the container with a listen port other than 5000 (e.g. `-e SLSKD_HTTP_PORT=6000`), the health check fails:
```
docker inspect --format "{{json .State.Health }}" slskd | jq
{
"Status": "unhealthy",
"FailingStreak": 1,
"Log": [
{
"Start": "2022-03-03T18:39:40.946050619-06:00",
"End": "2022-03-03T18:39:43.948265446-06:00",
"ExitCode": -1,
"Output": "Health check exceeded timeout (3s)"
}
]
}
```
This PR updates the health check to use the `SLSKD_HTTP_PORT` environment variable when making health checks.
```
docker inspect --format "{{json .State.Health }}" slskd | jq
{
"Status": "healthy",
"FailingStreak": 0,
"Log": [
{
"Start": "2022-03-03T18:43:50.040169257-06:00",
"End": "2022-03-03T18:43:50.284567916-06:00",
"ExitCode": 0,
"Output": "Healthy"
}
]
}
```
Closes #324
=> Use configured listen port for health check

src/slskd/Program.cs
At some point some properties were added to `Options` that were incompatible with the method the code that prints arguments and envars.  This code uses reflection to find properties, then creates instances of parent types to retrieve default values.  Certain types (like `string`) can't be instantiated with `Activator.CreateInstance`, and this was throwing.
The (perhaps lazy) solution is to swallow any errors encountered while traversing properties.
I verified that all of the arguments and envars are represented in the output, but I should probably check this periodically.
Closes #409
=> Fix --help and --envars flags

src/web/src/components/Transfers/TransferList.js, src/web/src/lib/util.js
Also changes `kbps` to `Kbps` to make size and bitrate labels consistent.
Closes #421
=> Disambiguate transfer size when less than 1 MB has been transferred

.github/workflows/ci.yml, Dockerfile
Reorders some directives in the Dockerfile to _maybe_ allow one or two additional layers to be cached (probably does nothing, but we'll see!)
Tweaks the buildx cache configuration to follow guidance from the build-push-action repo, here: https://github.com/docker/build-push-action/blob/master/docs/advanced/cache.md
=> Improve Docker caching in CI build

src/slskd/Core/API/Controllers/ApplicationController.cs, src/web/src/components/App.js, src/web/src/components/System/System.js, src/web/src/lib/application.js
I have been working on searches and fighting with this for the last two days.  The conclusion is that the UI can't operate properly behind a reverse proxy (when `url_base` is set) if it doesn't explicitly know which part of the current url is `url_base`.  There may be a clever way to deduce this that I'm missing, but for now I've added an unauthenticated endpoint `GET /urlbase` that allows the UI to explicitly fetch this when the `App` component is loading.  This allows it to explicitly prefix routes properly.
As a test I've implemented #441 and it works locally, but we'll see once I get it deployed.
=> Fix bug preventing routes with more than one segment from working

src/web/src/components/Search/Search.css, src/web/src/config.js
Also fixes a bug witn `urlBase` when debugging locally
Full width:
When sort order and toggles can't fit on one line anymore:
When the toggles can't all fit on one line anymore (mobile view, probably):
=> Update search control CSS

src/slskd/Common/Middleware/HTMLInjectionMiddleware.cs, src/slskd/Common/Middleware/HTMLRewriteMiddleware.cs
Recent work to fix some routing bugs with `urlBase` introduced a few middlewares to the ASP.NET pipeline; one to inject some javascript into static html files, and another to rewrite URLs in html links to include the base url.  Both of these middlewares rewrite the HTTP response, which includes resetting headers, status code, and body, and then re-writing.  
These middlewares worked, but I neglected to replace all of the response headers after rewriting the body, so `content-type` (among other things) was missing.  Lack of `content-type` caused the middleware to fight with one another, resulting in some static css and javascript files to have html appended, and causing upstream proxies to get confused about the response type.
This PR captures response headers and adds them back after …
=> Replace headers on rewritten HTML responses

Dockerfile
The Docker build takes forever, and I'd like to see how skipping testing impacts the speed.
Testing within the Docker build is somewhat redundant because the application is built and tested in a prior step during the build.  My original rationale was that if the container was built locally running the tests again would be a safety net.  I don't think I've ever done this, so if removing the tests can speed things up I may remove them permanently.
=> Skip tests in Docker build

Dockerfile
The Docker step took 20 minutes with tests disabled.  This isn't enough of an improvement to warrant skipping tests.
=> Revert skip tests in Docker build

src/slskd/Program.cs
`DataProtection` is for various built-in cryptography stuff that I'm not using (Cookies, request forgery keys, etc) but I can't turn it off.  The subsystem drops keys in an xml file by default in `~/.aspnet`; this PR forces the files to drop in `~/.local/share/slskd/data` instead.
=> Store data protection keys in slskd data dir

.github/workflows/ci.yml
It looks like the x86 runtime identifiers won't be added until .NET 7.  For now they'll have to come out.
I've confirmed that `osx-` RIDs are the same as `unix-`, but have decided to include both to hopefully cut down on any confusion.
=> Remove x86 binaries

src/slskd/Common/Extensions.cs, tests/slskd.Tests.Unit/Common/Extensions/ToLocalRelativeFilenameTests.cs
The existing code is expecting remote filenames to contain at least two parent directories (e.g. `@share\foo\bar.ext`); this isn't always the case.  
This PR refactors the logic to convert remote filenames to local filenames so that it returns only the file and the immediate parent.  If there is no parent, only the file is returned.
Closes #325
=> Fix bug downloading files from the root of a share

src/web/package-lock.json, src/web/src/components/Browse/Browse.js
The existing code relied on the first directory in the browse response to determine which path separator to use.  For some Nicotine+ users, the first directory is a single word.  This PR updates the separator detection logic to detect the first separator from the list of directories.
Closes #403
=> Fix bug affecting directory browsing of Nicotine+ users

src/web/src/components/Search/Detail/SearchDetail.js, src/web/src/lib/searches.js
Used in conjunction with `islossless`, `minbitdepth:24` can be specified to limit search results to only those with at least 24 bit depth.
Closes #514
=> Add 'minbitdepth' filter for search results

src/web/src/components/LoginForm.js
For some reason if I use Form.Input for the component the ref is always undefined, so had to switch it to Input.
Fixes #507
=> Focus on username input field on load.

src/slskd/Application.cs, src/slskd/Core/Extensions.cs, src/slskd/Core/State.cs, src/slskd/Messaging/API/Controllers/ConversationsController.cs, src/slskd/Messaging/API/Controllers/RoomsController.cs, src/web/src/components/App.js, src/web/src/components/System/Info/index.js, src/web/src/components/System/Options/index.js
Adds tracking of the logged in user's privileges client-side.  Adds a button users can click to navigate to the Soulseek donation page:
Adds a small star icon to indicate privileged status:
Closes #536 
Closes #535 
Also stops sorting info and options yaml.
=> Track user privileges

src/slskd/Application.cs, src/slskd/Core/ConnectionWatchdog.cs, src/slskd/Core/State.cs, src/slskd/Program.cs
The existing reconnect logic executes when a `Disconnected` event fires, and this event can fire while the client is attempting a connection, which causes the reconnect logic to be executed again, and ultimately a ton of reconnect attempts are made concurrently.
I could have added a semaphore to prevent this re-entrance, but there was no good way to ensure that reconnect logic would continue to execute if a connection connected successfully, but disconnected before the semaphore was released.
This PR adds a `ConnectionWatchdog` class that uses a timer to check the status of the connection and if the client is disconnected, the reconnect logic is executed.  The watchdog starts when a qualifying disconnect event is fired, and stops when a connect event is fired.
There shouldn't be a way for …
=> Move reconnect logic to ConnectionWatchdog

src/slskd/Search/API/Controllers/SearchesController.cs, src/slskd/Search/ISearchService.cs, src/slskd/Search/SearchService.cs
Currently, the search state is only persisted at the start and end of the search; updates are streamed to the browser via SignalR only.
If a user starts a search and then refreshes their browser, it will appear as though the search was started but had not received any updates because this is the only information the database has, and data is sent to the browser on first load straight from the db.
With this update, the database is updated when status changes are broadcast, so if a browser is refreshed (or if someone is monitoring the search over the REST API) the data should be in sync.
This was identified as a shortcoming of the search API as I was working on persisting transfer data, and the same applies there.
=> Persist search status to the database as the search is running

src/slskd/Common/Dumper.cs, src/slskd/Core/API/Controllers/ApplicationController.cs
Every once in a while I catch the app using a lot more memory than normal and wish I could get a dump to figure out what's consuming it, but getting into the container, producing a dump, and then getting it back out is too much hassle.
This PR adds some functionality that downloads `dotnet-dump` from Microsoft, executes it to produce a `.dmp` file, and then returns the file for downloading.
=> Add an API endpoint to create and retrieve memory dumps

Dockerfile
`dotnet-dump` throws this error, because .NET framework is not installed in the container:
```
A fatal error occurred. The required library libhostfxr.so could not be found.
If this is a self-contained application, that library should exist in [/var/tmp/.net/p1tya53k.oek/S2drLjKvIRWJ8Ptc7UtAKpJNqfC5ivU=/].
If this is a framework-dependent application, install the runtime in the global location [/usr/share/dotnet] or use the DOTNET_ROOT environment variable to specify the runtime location or register the runtime location in [/etc/dotnet/install_location].
The .NET Core runtime can be found at:
- https://aka.ms/dotnet-core-applaunch?missing_runtime=true&arch=x64&rid=debian.11-x64
[] [13:20:06 ERR] An unhandled exception has occurred while executing the request. …
```
=> Temporarily use runtime image to enable memory dumps

Dockerfile
The runtime memory dump idea fell flat; dependencies are missing and I'd have to use the SDK image moving forward (and it still didn't work).
This can still work, but not within this Docker image.
=> Switch back to runtime-deps base image

src/slskd/Application.cs, src/slskd/Common/Logging/ConsoleWriteLineLogger.cs, src/slskd/Program.cs
In the few places where `Console.WriteLine` is needed, use a try/catch.  
Related to #556 (I think)
=> Remove console logging in favor of logger abstraction

config/slskd.example.yml, docs/config.md, src/slskd/Application.cs, src/slskd/Core/Options.cs
Previously any incoming search of less than 3 characters was discarded.  This was mostly a carry-over from when the application was being built as an example/testing platform for Soulseek.NET.
This PR adds the ability to configure a list of regular expressions that, when matched with an incoming search request, cause the request to be discarded.
By default there is no filtering.
=> Add the ability to filter incoming search requests

Dockerfile, src/slskd/Application.cs, src/slskd/slskd.csproj
I'm still trying to figure out how much of the memory usage reported in #553 is just idiomatic .NET garbage collection, and how much of it is an application memory leak.
This PR implements the most relevant GC settings as environment variables in the Dockerfile, which should give users a better idea of default behavior if they want to tweak things for their environment.
This change also implements a hard memory limit of 500mib.  The rationale is that if the application has a legitimate memory leak, it will eventually crash when it hits this limit (as opposed to GC increasing pressure).
I have still been unsuccessful in retrieving a memory dump for an inexplicably long list of reasons.
=> Tweak options related to garbage collection

src/slskd/Transfers/API/Controllers/TransfersController.cs, src/slskd/Transfers/API/DTO/DirectoryResponse.cs
I inadvertently broke a bunch of stuff on the UI by renaming this property from `Directory` to just `Name`.  This PR changes it back.
Fixes:
* Missing directory name on groups of files
* File selection and actions not working
=> Rename DirectoryResponse Name prop to Directory

src/slskd/Application.cs, src/slskd/Transfers/Downloads/DownloadService.cs, src/slskd/Transfers/Downloads/IDownloadService.cs, src/slskd/Transfers/Uploads/IUploadService.cs, src/slskd/Transfers/Uploads/UploadService.cs
Previously these records were being updated with 'fire and forget' async method calls, which _I believe_ were causing out-of-order updates and potentially leaving records in a state other than what should have been the terminal state in the database.
Potentially related to #598
=> Synchronously update transfer database records

src/slskd/Program.cs, src/slskd/Transfers/TransfersDbContext.cs
A user in Discord reported errors deleting transfers:
```
Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 5: 'database is locked'
```
I believe this is due to the change to synchronous updates introduced in #599.  I did a bunch of research and came up with two things that might fix the issue, the first being to set the connection to use pooling via the connection string, and the second to set SQLite into multithreading mode, which I was surprised to discover is not the default.
=> Add sqlite pooling, set multithreading mode

src/slskd/Application.cs, src/slskd/Core/State.cs, src/slskd/Shares/API/Controllers/SharesController.cs, src/slskd/Shares/IShareService.cs, src/slskd/Shares/ShareService.cs, src/slskd/Shares/SharedFileCache.cs
=> Make share scanning log more verbosely in debug mode, and a little easier on memory

src/slskd/Application.cs, src/slskd/Common/ExponentialMovingAverage.cs, src/slskd/Core/API/Controllers/MetricsController.cs, src/slskd/Core/Clock.cs, src/slskd/Core/Metrics.cs, src/slskd/slskd.csproj
Also exposes Prometheus metrics via `/api/v0/metrhcis` in addition to the existing `/metrics`
Closes #613
=> Add metrics tracking search and browse activity and distributed network state

src/slskd/Common/Middleware/HTMLInjectionMiddleware.cs, src/slskd/Program.cs
Now checks the response content type in addition to the request, in case a controller returns a type other than what was requested (as was the case for Prometheus).
Adds the ability to explicitly exclude routes by path, and excludes `/api` and `/swagger`.
Closes #614
=> Fix bug causing html to be injected in prometheus metrics

config/slskd.example.yml, docs/config.md, src/slskd/Core/API/Controllers/MetricsController.cs, src/slskd/Core/Metrics.cs, src/slskd/Core/Options.cs, src/slskd/Program.cs
Previously, the `/metrics` endpoint publishing Prometheus metrics wasn't able to be authenticated.  I didn't think this was a big deal at first, but somewhere along the way I enabled collection of system metrics and with these came things like OS, architecture, and most concerningly, drive mount points.  These aren't exactly secret, but it does give an attacker a lot of information about my system that could be used to exploit vulnerabilities.
This PR reworks the metrics implementation to add basic authentication (the type used by Prometheus) and allows users to set the endpoint.
Note that this is a breaking change for people using Prometheus today; the `features.prometheus` setting has been removed in favor of `metrics.enabled`.  Because metrics are disabled by default, metrics …
=> Refactor Prometheus implementation and add basic authentication for the /metrics endpoint

src/slskd/Application.cs, src/slskd/Common/CommonExtensions.cs, src/slskd/Core/Options.cs, src/slskd/Shares/IShareService.cs, src/slskd/Shares/ShareService.cs, src/slskd/Shares/SharedFileCache.cs, src/slskd/Transfers/Uploads/UploadService.cs
This has been a contentious issue, with compatibility all over the place across various clients.  This PR should solve this once and for all by standardizing on using backslashes for file paths everywhere.
Two new extension methods have been added: `NormalizePath()`, which accepts a file path and returns that path with backslashes, and `LocalizePath()`, which accepts a file path and returns that path with slashes localized to the local OS.  This is important because most of the functionality in the BCL living in `System.IO.Path` relies on the `System.IO.Path.DirectorySeparatorChar` value, meaning if you try to manipulate a path using backslashes on Linux, it's not going to work the way you expect because it assumes your characters are forward slashes.
`NormalizePath()` _must_ be used to …
=> Normalize file path separators to backslashes

src/slskd/Application.cs, src/slskd/Common/SqliteConnectionExtensions.cs, src/slskd/Core/ConnectionStrings.cs, src/slskd/Core/Filenames.cs, src/slskd/Core/Options.cs, src/slskd/Core/State.cs, src/slskd/Program.cs, src/slskd/Shares/IShareService.cs, src/slskd/Shares/ISharedFileCache.cs, src/slskd/Shares/ShareService.cs, src/slskd/Shares/SharedFileCache.cs, src/slskd/slskd.csproj
Currently shared files are stored in memory within an SQLite database (for full text search) and in a dictionary (for metadata).  This is fast, but uses a lot of memory and large shares cause the application to crash, as reported in #610.
This PR refactors the cache to store all data on disk, and to load the cache from disk on start, negating the need to scan on every start.
These changes allow very large collections to be shared, but negatively impacts the performance of search and browse response creation.
A future update will add an option to use on-disk or in-memory storage so users can select the strategy that works best for their collection.
Remaining tasks:
=> Refactor shared file cache to store all data on disk

src/slskd/Shares/SharedFileCache.cs
With full physical filenames now being stored in the shared file cache (#637), paths don't need to be manipulated and backslashes won't cause any issues locally.  There may be compatibility issues with some clients, especially those on Windows, but we'll see.
Closes #628
=> Remove warnings about backslashes in file or directory names

src/slskd/Shares/SharedFileCache.cs
Search results are sorted by SQLite, and the code erroneously sorts them again before returning.  This should improve response times a little bit.
=> Don't double sort search results

src/slskd/Shares/SharedFileCache.cs
Other SQLite databases managed by Entity Framework have the journal mode set to WAL by default.  The shared file cache database is created without EF, and therefore WAL needs to be enabled explicitly.
=> Set shared file cache journal mode to WAL

src/slskd/Application.cs, src/slskd/Common/ChannelReader.cs, src/slskd/Core/API/Controllers/ApplicationController.cs, src/slskd/Core/State.cs, src/slskd/Program.cs, src/slskd/Shares/API/Controllers/SharesController.cs, src/slskd/Shares/IShareService.cs, src/slskd/Shares/ISharedFileCache.cs, src/slskd/Shares/ShareService.cs, src/slskd/Shares/SharedFileCache.cs, src/web/src/components/System/Shares/index.js, src/web/src/components/System/System.css, src/web/src/lib/shares.js
I decided to tackle a bunch of stuff all at once:
* Adds an application-level cancellation token to help things shut down in a timely manner, especially when a scan is in progress
* Adds the ability to cancel share scans, along with an API endpoint and button on the UI
* Fixes a number of issues with share counts and state (reverses a bug that was added recently)
* Vastly improves the performance of the display of share configuration
* Forces a share scan if the application can't load the shared file cache on start (this also fixes the issue with share counts/status being unknown, as shares are either loaded, or scanned at startup)
* Updates the UI every 1% of scan progress, instead of 5% (this is all the monitoring I want to provide at the moment)
Closes #490 
Closes #443 
Closes #532
=> Add the ability to cancel a share scan

docs/config.md, src/slskd/Core/Options.cs
The previous default (16) was causing the application to become unresponsive during a scan, depending on the system the app was running on.  This PR uses what it believes is the processor count of the system, which should be the best for most people.
I guess I should note that the performance of the scan has a lot more to do with I/O performance than CPU so this might not make a lot of sense for some systems, but it's better than using a static value.
Closes #659
=> Default scan workers to Environment.ProcessorCount

src/web/src/components/Transfers/Transfers.css
Reduced the 6px of ```padding-top``` for ```transfers-header-segment```.
Added ```margin-top``` property to ```transfers-segment-icon``` class to position icons appropriately.
=> Fixed padding-top to 14px for transfers-header-segment

src/slskd/Shares/SharedFileCache.cs
Currently filters are checked against files as they are being scanned, but not directories.  This can leave a bunch of empty directories in the share.
Closes #665
=> When scanning shares, apply filters to directories as well as files

src/web/src/components/Search/Detail/SearchDetail.js
This PR should fix an issue with displaying a 'Stop' button in the SearchDetailHeader instead of 'Delete' and 'Search Again' when viewing a search that returned no results.
Closes #648
=> Display the correct buttons in the header when viewing a search that returned no results

src/slskd/Application.cs
A user in Discord reported an error in this logic that suggests a zero was somehow passed to `SendUploadSpeedAsync`.  The value may have been zero because the transfer completed abnormally quickly, or the value may have been less than 1, resulting in some internal rounding that produced `0` when converted to an `int`.
This PR uses `Math.Ceiling` to ensure any nonzero `double` winds up a nonzero integer.
=> Fix potential bug when reporting upload speed

docs/config.md, docs/docker.md
- Added SLSKD_ before all env variables described in ```config.md```
- Edited line suggesting SLSKD_ is omitted in rest of the file
- Updated ```SHARED_DIR``` in docker.md to ```SLSKD_SHARED_DIR```
=> Update docs to prefix environment variables with SLSKD_

src/slskd/Program.cs
Adding this broke the existing JWT authentication, leaving users unable to log in to the UI.
Closes #677
=> Temporarily disable API key authentication

src/slskd/Common/Authentication/AuthPolicy.cs, src/slskd/Core/API/Controllers/ApplicationController.cs, src/slskd/Core/API/Controllers/MetricsController.cs, src/slskd/Core/API/Controllers/OptionsController.cs, src/slskd/Core/API/Controllers/ServerController.cs, src/slskd/Core/API/Controllers/SessionController.cs, src/slskd/Core/API/Hubs/ApplicationHub.cs, src/slskd/Core/API/Hubs/LogsHub.cs, src/slskd/Messaging/API/Controllers/ConversationsController.cs, src/slskd/Messaging/API/Controllers/PublicChatController.cs, src/slskd/Messaging/API/Controllers/RoomsController.cs, src/slskd/Program.cs, src/slskd/Search/API/Controllers/SearchesController.cs, src/slskd/Search/API/Hubs/SearchHub.cs, src/slskd/Shares/API/Controllers/SharesController.cs, src/slskd/Transfers/API/Controllers/TransfersController.cs, src/slskd/Users/API/Controllers/UsersController.cs
#674 added the ability to authenticate API calls with an API key, which worked for API keys but broke the existing JWT implementation, and had to be rolled back in #678.
After some trial and error and combing through unhelpful ASP.NET documentation, I've concluded that the only way to support two different authentication schemes concurrently is to use the built in `Policy` stuff, so this PR adds that.
I was planning to restrict remote editing of options to JWTs at some point, and this was a great opportunity to add that as well.  Endpoints that use the `AuthPolicy.JwtOnly` policy can only be used when the caller has authenticated with a JWT.  The rationale is that API keys are more likely to be leaked or stolen, and because they don't expire, they pose a greater security risk.  There's …
=> Add authorization policies

src/slskd/Common/Exceptions/ShareInitializationException.cs, src/slskd/Shares/ShareRepository.cs, src/slskd/Shares/ShareScanner.cs, src/slskd/Shares/ShareService.cs
Previously the schema validation logic only checked for the three main tables; it now checks the entire schema (less indexes) to be extra sure.
I also refactored the initialization logic because it had some conditionals that were difficult to understand.
This should hopefully prevent cases when a 'bad' database file passes validation and causes problems.
Related to #683
=> Implement more explicit schema checks when initializing the shared file cache

src/slskd/Program.cs
- This PR addresses #633 
- It makes changes to ```Program.cs``` and ```contentPath```
- It avoids using the absolute path which can allow for security issues, and instead lets the user give relative paths with respect to the application directory.
=> Update contentPath to use AppContext.BaseDirectory

Dockerfile
Based on [the tini docs](https://github.com/krallin/tini#existing-entrypoint).
Closes #702
=> Add tini to docker image

src/slskd/Shares/IShareRepository.cs, src/slskd/Shares/ShareService.cs, src/slskd/Shares/SqliteShareRepository.cs
I was able to verify this morning that in-memory databases are likely to be destroyed after the application has been running for some time.  When this happens logs fill up with errors due to failed search lookups, as reported in #683.
According to [SQLite documentation](https://www.sqlite.org/inmemorydb.html),
>  The database is automatically deleted and memory is reclaimed when the last connection to the database closes.
Searches come in from the network continuously, and each causes a new connection to be created and the `filenames` table queried.  It should be very unlikely for this problem to occur, but clearly it is.
As a workaround I've added a new `KeepaliveConnection` to go with each share database.  This connection is opened when the share repository is created, and only closed …
=> Add keepalive for share databases

config/slskd.example.yml, src/slskd/Application.cs, src/slskd/Common/Authentication/ApiKeyAuthentication.cs, src/slskd/Common/Authentication/Role.cs, src/slskd/Common/CommonExtensions.cs, src/slskd/Common/Exceptions/OutOfRangeException.cs, src/slskd/Core/API/Controllers/SessionController.cs, src/slskd/Core/Options.cs, src/slskd/Core/Security/SecurityService.cs, src/slskd/Network/API/Controllers/NetworkController.cs, src/slskd/Network/NetworkClient.cs, src/slskd/Program.cs
It turns out the existing code I wrote to handle API keys with SignalR didn't work.  This PR makes it work, and allows users to optionally ignore certificate errors when connecting to a controller over HTTPS, but when the controller doesn't have a valid certificate (such as when it is self signed, as slskd uses by default)
=> Rework API authentication

src/slskd/Shares/ShareScanner.cs, src/slskd/Shares/ShareService.cs, src/slskd/Transfers/Uploads/UploadService.cs
I thought I was in a good place with this, but now am encountering issues with the new network mode where the agent and controller are using different operating systems.  The path localization logic doesn't work for these because the masked paths saved in the shared file database use localized slashes.
This PR updates the scanner logic to save masked files with backslashes, regardless of operating system.  There's no longer a need to normalize paths on the way out to the network, so that logic is removed.
I'm really not sure why I didn't just do this in the first place; it's the much more logical option.  I'll probably find out when new bugs surface after this is merged 🙃
=> Normalize all paths shared with the Soulseek network to use backslashes

src/slskd/Application.cs, src/slskd/Network/NetworkClient.cs
This may lead to redundant uploads on start if the controller connection is ever established prior to share initialization.  It should be obvious, and I doubt the ordering would ever change, anyway.
=> Upload shares to controller after a local scan

config/slskd.example.yml, src/slskd/Application.cs, src/slskd/Core/Options.cs
Prevents blacklisted users from:
* Receiving search results
* Browsing files
* Retrieving directory contents
* Enqueueing downloads
Adding someone to the blacklist doesn't cancel transfers in flight; users will need to do that themselves.
This could be expanded to ignore messages in chat rooms and private messages, but that's probably best done separately for now.
=> Add blacklist for files

src/slskd/Shares/SqliteShareRepository.cs
#723 changed how paths are stored in the share database, and @mathiascode correctly reminded me that I'd need a migration path for existing databases.  I, of course, forgot all about that when I created the [0.16.28 release](https://github.com/slskd/slskd/releases/tag/0.16.28) last night, and anyone that happened to update right away is probably broken.
This PR introduces a new `version` table to the SQLite database that stores shares.  This table has a single integer column, `a`.
The code checks the database layout on start, and if the expected layout doesn't match the file, the existing file is discarded and shares are re-scanned. 
Moving forward, when I introduce a breaking change to this database (or any other ephemeral database, like searches), I'll change the name of the column in …
=> Add version table to shares db

config/slskd.example.yml, src/slskd/Application.cs, src/slskd/Common/Exceptions/RelayException.cs, src/slskd/Core/Options.cs, src/slskd/Core/State.cs, src/slskd/Program.cs, src/slskd/Relay/API/Controllers/RelayController.cs, src/slskd/Relay/API/Hubs/RelayHub.cs, src/slskd/Relay/DummyRelayClient.cs, src/slskd/Relay/RelayClient.cs, src/slskd/Relay/RelayClientState.cs, src/slskd/Relay/RelayService.cs, src/slskd/Relay/Types/Agent.cs, src/slskd/Relay/Types/OperationMode.cs, src/slskd/Transfers/Uploads/UploadService.cs
This was confusing me a bit, and it's fresh in my mind.  Relay is a more descriptive name anyway.
=> Rename 'Network' functionality to 'Relay'

.github/workflows/ci.yml
#679 (thanks again @Exouxas!) fixed the invalid version issue that would cause build failures [like this](https://github.com/slskd/slskd/actions/runs/3509143301/jobs/5878035956#step:6:19) when building locally, but at the time I had forgotten that the version is computed in CI as well as in the build script.  
This PR updates the delimiter in CI to match the build script.
=> Use + version delimiter in CI

.github/workflows/ci.yml
#763 switched to using `+` to delimit the version number and SHA in CI builds, but Docker [found this disagreeable](https://github.com/slskd/slskd/actions/runs/3509230976/jobs/5878200714#step:9:118).
=> Revert + version delimiter for docker tags

docs/config.md, src/slskd/Application.cs, src/slskd/Relay/API/Controllers/RelayController.cs, src/slskd/Relay/API/Hubs/RelayHub.cs, src/slskd/Relay/RelayClient.cs, src/slskd/Shares/ShareService.cs
Updates docs, fixes a bunch of logging issues, and tweaks the `Ready` state change of the shares service to delay the update until after share statistics are re-computed.
Closes #769 
Closes #770 
Closes #771
Closes #772
=> Relay tweaks and bug fixes

src/slskd/Relay/API/Controllers/RelayController.cs, src/slskd/Relay/API/Hubs/RelayHub.cs, src/slskd/Relay/RelayClient.cs, src/slskd/Relay/RelayService.cs, src/slskd/Transfers/Uploads/UploadService.cs, src/slskd/slskd.csproj
The initial implementation would only upload entire files, and the stream that comes from the HTTP controller receiving the files isn't capable of seeking, so resumed uploads would fail.
This PR updates Soulseek.NET to a new preview version that passes the requested start offset down to the input stream factory of `UploadAsync()`, and adds an option to turn off automatic seeking of input streams, offloading that responsibility to the caller (slskd, in this case).
The Relay controller now passes the start offset down to the agent, and the agent seeks the file stream prior to uploading.
Tested and confirmed working for both agent and non-agent (local) uploads.
Closes #768
=> Add support for resume-able uploads from Relay Agents

src/slskd/Core/API/Controllers/ServerController.cs, src/slskd/Messaging/API/Controllers/ConversationsController.cs, src/slskd/Messaging/API/Controllers/PublicChatController.cs, src/slskd/Messaging/API/Controllers/RoomsController.cs, src/slskd/Program.cs, src/slskd/Search/API/Controllers/SearchesController.cs, src/slskd/Transfers/API/Controllers/TransfersController.cs, src/slskd/Users/API/Controllers/UsersController.cs
This adds an `IsRelayMode` property to `Program` which is statically available everywhere.  The logic now tests for `Enabled` in addition to the mode being set.
=> Add IsRelayAgent to Program, simplify checks

.github/workflows/ci.yml, docs/system_requirements.md
=> Add ARMv6 (Raspberry Pi 1/Zero) support by including linux-armv6 binaries in releases

src/slskd/Users/API/Controllers/UsersController.cs, src/slskd/Users/API/DTO/DirectoryContentsRequest.cs, src/web/src/components/Search/Response.js, src/web/src/lib/users.js
This tweaks the existing API logic to pass the directory name in a POST body instead of a GET route, which fixes a bunch of encoding issues that can't be overcome with ASP.NET (like forward slashes in a route, even if they are URL encoded)
Closes #792
=> Fix 404 when retrieving directory contents

config/slskd.example.yml, docs/config.md, src/slskd/Core/Options.cs, src/slskd/Relay/API/Controllers/RelayController.cs, src/slskd/Relay/API/Hubs/RelayHub.cs, src/slskd/Relay/RelayClient.cs, src/slskd/Relay/RelayService.cs, src/slskd/Transfers/Downloads/DownloadService.cs
The controller notifies each connected agent when each download is completed.  Agents will, if the `downloads` option is set, download those files from the controller over HTTP/S and store them in their local directory.
Closes #787
=> Add the ability to configure Relay Agents to download files downloaded by the controller

src/slskd/slskd.csproj
This will stop the `Warning` logs related to text encoding.
=> Bump Soulseek.NET to 6.1.1

src/slskd/Core/API/Controllers/OptionsController.cs, src/web/src/components/System/Options/index.js
Currently the debug view of config could be retrieved if remote config is disabled and the application isn't run in debug mode.  This PR forbids this endpoint if either of those is true.  Additionally, the UI button is not shown if remote config is disabled.
Note that this endpoint still requires a valid JWT, so the endpoint isn't completely unauthorized.
Additionally this change forbids retrieval of the yaml location and validation of yaml if remote config is disabled.  Neither of these endpoints changes or exposes config, but there's no reason they need to be functional if remote config isn't enabled.
=> Increase security of config-related API endpoints

src/slskd/Application.cs
Presently it is impossible to start the application in Relay mode if no Soulseek credentals are specified.  This PR refactors the startup logic to enable this.
=> Tweak startup logic

src/slskd/Program.cs
=> Refactor the --generate-secret command to produce a friendlier error if the user doesn't supply a value

src/slskd/Application.cs, src/slskd/Common/CommonExtensions.cs, src/slskd/Core/API/DTO/TokenResponse.cs, src/slskd/Program.cs, src/slskd/Relay/DummyRelayClient.cs, src/slskd/Relay/RelayClient.cs, src/slskd/Shares/API/Controllers/SharesController.cs, src/slskd/Shares/SqliteShareRepository.cs, src/slskd/Transfers/API/Controllers/TransfersController.cs, src/slskd/Users/API/Controllers/UsersController.cs, tests/slskd.Tests.Unit/Transfers/Uploads/UploadQueueTests.cs
I saw a remote agent log in and try to upload shares and it was rejected with an unauthorized message.  This was a race condition, but one that spanned a network.  I added a 500ms delay prior to uploading shares that should help with this.
=> Fix a bunch of linter warnings, include share upload in agent connection retry loop

.github/workflows/ci.yml
A number of `docker` GitHub actions have been updated, and the `build-push` action now natively supports GitHub as a layer cache.  This PR updates the actions and deprecates the manual caching in favor of native.
=> Simplify docker caching

src/slskd/Program.cs
A while ago I tried to use `+` to delimit the semantic version and the SHA it is based on to better conform to semver.  This worked with some things and broke others, so I reverted it.  I neglected to update the logic that parses the semantic version, leaving the `+` in place.  This would periodically break the version check because of .NET's versioning rules.
This PR swaps `+` for `-` and fixes the version check, hopefully for good.
Closes #705 
Related to #763
=> Fix bug parsing semantic version

src/web/src/components/Transfers/TransferList.js
Instead of only showing the file size when some bytes have been downloaded always show it. That way a user knows the size of pending downloads too.
Fixes #600
=> Always show file size when downloads are cancelled or pending

src/web/src/components/App.js, src/web/src/components/Search/Searches.js
There were 2 issues here:
1. The Redirect in App.js seems to be being hit on reload always and would always force a redirect. I tried googling but couldn't find a good answer why and how to workaround it, so I've just excluded our known paths from that redirect.
2. Even after this in Searches.js there's a race condition with the component being connected and starting to process the searchId, but the searches haven't been set yet, so it assumes it's invalid and resets to /searches. So I've swapped the order in onUpdate and that seems to fix it with no side effects.
Fixes #555
=> Fix browser reload to stay on the same page

src/slskd/Program.cs
An analyzer was added somewhere in the recent past that is griping about using top level endpoint mapping.  I tried it and it broke everything.  I don't like seeing this warning in builds and I don't think it should be an analyzer in the first place, so I'm disabling it.
It can be revisited later if someone else wants to figure it out.
=> Suppress ASP0014

Dockerfile
Per a Discord conversation with a user experiencing a crash when running the container with `podman kube play`, the `/var/tmp` mount negatively interacts with the .NET bundle that gets extracted to the same place, leading to a crash following a failure to access binaries related to SQLite3.
This PR moves the extraction location to `/slskd`, which will reside next to the rest of the application.  This may cause issues for other .NET apps that might run inside of the same container, but I'm comfortable saying that this use case is 1) weird, and 2) not supported.
=> Move dotnet bundle location within the Docker container to /slskd

Dockerfile
=> Move .NET bundle extraction location to /.net, set proper permissions

.github/workflows/ci.yml
Closes #904 
Related to #905 
I had been trying to keep this list on the shorter side so that the list of binaries in the GitHub release wouldn't need to be expanded to find the most common platforms.  Prior to this only one of the `arm` binaries was hidden; after this is merged there will be more.
=> Add x86 and freebsd runtime targets

.github/workflows/ci.yml
Unfortunately these runtime targets aren't fully supported.  The [release build](https://github.com/slskd/slskd/actions/runs/4963214686) failed with:
```bash
There is no application host available for the specified RuntimeIdentifier 'linux-musl-x86'.
There is no application host available for the specified RuntimeIdentifier 'linux-x86'.
The specified RuntimeIdentifier 'freebsd-arm64' is not recognized.
There is no application host available for the specified RuntimeIdentifier 'freebsd-x64'.
```
The `win-x86` RID didn't raise any issues, but there's dubious value in including that (I think the last 32 bit Windows OS is XP?).
=> Revert "add x86 and freebsd runtime targets"

docs/config.md, src/slskd/Core/Options.cs, src/web/src/components/System/Files/Explorer.js, src/web/src/components/System/Files/index.js, src/web/src/components/System/System.js
Related to #205 
Also addresses one of the issues reported in #942, specifically a validation failure if no shares are defined.
=> Document remote file management option, remove delete icons from UI when option is disabled

config/slskd.example.yml, docs/config.md, src/slskd/Application.cs, src/slskd/Core/Clock.cs, src/slskd/Core/Options.cs, src/slskd/Program.cs
#972 added the ability to configure the application to remove transfers from the UI automatically after a configurable amount of time.  This PR adds similar settings for files on disk (both downloaded and incomplete) and application logs.
=> Add automated removal of downloaded and incomplete files, and application logs

config/slskd.example.yml, docs/config.md, src/slskd/Application.cs, src/slskd/Core/Options.cs
With the addition of file and log retention options in #979, the transfer retention options would create confusion in users regarding the difference between 'upload', 'download' and 'files' retention options.  This move should clear things up.
This will be a breaking change for anyone that has added retention options for transfers.
=> Move transfer retention options

.github/workflows/ci.yml
The 0.19.0 release build keeps hanging, and I'm not sure why.  It seems the last couple of logs before it times out are always related to the arm/v7 image, so I'm temporarily removing it from the build matrix to see if that's the cause.
It takes a long time to build this image because of the emulation required, and I think it has dubious value now that the Raspberry Pi 3 has been out over 5 years; this image is intended for RPI 2 users, and those with a 32 bit OS on an RPI 3.
=> Stop building arm/v7 Docker images

src/slskd/slskd.csproj
Soulseek.NET 6.1.3 fixes a [bug](https://github.com/jpdillingham/Soulseek.NET/pull/792) causing a confusing message when the address of the server fails DNS resolution.
Previously the exception was:
```
Soulseek.AddressException: Failed to resolve address '': Resource temporarily unavailable
```
It should now be:
```
Soulseek.AddressException: Failed to resolve address 'vps.slsknet.org': Resource temporarily unavailable
```
=> Update dependencies, including Soulseek.NET to 6.1.3

config/slskd.example.yml
Minor typo in the default slskd config (`queue_strategy` vs `strategy`
=> Minor fix in the user-defined queue strategy parameter

config/slskd.example.yml, docs/config.md, src/slskd/Application.cs, src/slskd/Core/API/Controllers/ServerController.cs, src/slskd/Core/ConnectionWatchdog.cs, src/slskd/Core/Options.cs
Previously the application used the address and password that were hard-coded in the Soulseek.NET library.  The recent DNS related outage created a need for users to be able to substitute an IP address for the hostname, and this PR adds that ability.
Users can also change the port, but I'm not sure why someone would want to do that.  The official client has a lot of ports to choose from for some reason.
Users generally shouldn't need to set these.
=> Add options for the Soulseek server address and port

docs/docker.md
I added some words explaining the `--user`/`user:` specification in Docker, and updated the existing examples to include the relevant options.
I have also added `docker-compose` examples for the sake of completeness.
Closes slskd/slskd#473.
=> Explain docker --user, add compose examples

.github/workflows/ci.yml, Dockerfile
It seems like several other people have solved the hanging issue by pinning the node docker image to v18, so I'll try it, too.
Closes #987
=> Re-enable ARMv7 Docker images

config/slskd.example.yml, docs/config.md, src/slskd/Application.cs, src/slskd/Common/Validation/IPAddressAttribute.cs, src/slskd/Core/Options.cs
Functional tests still required:
~~There's a slight chance that the logic Soulseek.NET isn't working, as I didn't test that thoroughly.~~ Works fine!
=> Add the ability to specify a local IP address to listen on

src/slskd/slskd.csproj
This pulls in the Soulseek.NET change to add a write semaphore, preventing concurrent messages to the same user from interleaving and breaking things like browse and search responses.
=> Bump Soulseek.NET to 6.3.0

src/slskd/Core/API/Controllers/ApplicationController.cs, src/slskd/Core/API/Controllers/LogsController.cs, src/slskd/Core/API/Controllers/MetricsController.cs, src/slskd/Core/API/Controllers/OptionsController.cs, src/slskd/Core/API/Controllers/ServerController.cs, src/slskd/Core/API/Controllers/SessionController.cs, src/slskd/Files/API/FilesController.cs, src/slskd/Messaging/API/Controllers/ConversationsController.cs, src/slskd/Messaging/API/Controllers/PublicChatController.cs, src/slskd/Messaging/API/Controllers/RoomsController.cs, src/slskd/Program.cs, src/slskd/Relay/API/Controllers/RelayController.cs, src/slskd/Search/API/Controllers/SearchesController.cs, src/slskd/Shares/API/Controllers/SharesController.cs, src/slskd/Transfers/API/Controllers/TransfersController.cs, src/slskd/Users/API/Controllers/UsersController.cs, src/slskd/slskd.csproj
I diffed the generated openapi spec against the canary and it's the same.
=> Replace deprecated versioning package

config/slskd.example.yml, docs/config.md, src/slskd/Core/API/Controllers/OptionsController.cs, src/slskd/Core/Options.cs, src/slskd/Program.cs
Setting this option to `true` will prevent the application from reacting to changes in the configuration file.  The remote configuration feature relies on this functionality, so with this enabled the configuration can be changed remotely but no changes will take effect until the application is restarted.
Related to #1050
=> Add 'NoConfigWatch' flag to suppress config file watching

src/web/src/components/Chat/Chat.css
Various improvements to the colours in chats:
- Increase contrast of text in dark theme.
- Make the text colour in the light theme a little nicer.
- Improve the contrast of message timestamps.
- Add a subtle background to messages sent by the local user, in both themes, to help distingish message boundaries.
Screenshot of the changes:
These colours have been confirmed to meet APCA contrast guidance.
This should largely resolve #1017.
=> Improve chat colours

config/slskd.example.yml, src/slskd/Application.cs, src/slskd/Core/Options.cs
Sometimes users repeatedly try and fail to download files, and at some point it just isn't going to work and they need to stop trying.
This limit helps users get the hint; when the configured number of failures is reached, users can no longer enqueue files, and are given a response like 'Too many failed transfers today'.
Extension of #1035 
Part of of #388
=> Add a configurable limit for number of daily and weekly failed transfers

src/slskd/Application.cs
I had forgotten that the standard [transfer rejection messages](https://nicotine-plus.org/doc/SLSKPROTOCOL.html#in-use) are used by other clients to determine whether to retry a transfer.  This PR adjusts the message returned when exceeding queue limits so that other clients will retry.
If daily or weekly limits have been exceeded, different messages will be sent and those transfers will not be automatically retried.
=> Return proper message when exceeding queued limits

config/slskd.example.yml, docs/config.md, src/slskd/Common/TokenBucket.cs, src/slskd/Core/Options.cs, src/slskd/Transfers/Uploads/UploadGovernor.cs
Speed limits are all expressed in kibibytes.  It took me some investigation to validate this, so I've left indicators in the code as well as added a few to the docs.
Closes #1078
=> Add speed limit units to code, docs

src/slskd/Application.cs, src/slskd/Shares/SqliteShareRepository.cs
Starting earlier this year and prompted by an increase in copyright trolling, the server began to send a list of "excluded search terms" which is intended to be used by clients to perform filtering on outgoing search results.  This PR implements that functionality.
This may be objectionable to some but it's for the good of the network, and we all need to be prioritizing that if we want it to stick around.
See also: https://github.com/jpdillingham/Soulseek.NET/issues/803
=> Add compliance with server code 160/ExcludedSearchPhrases

src/slskd/Core/Options.cs, src/slskd/Program.cs
This is a breaking change for anyone that has manually specified a JWT signing key with a length of fewer than 32 characters.  If the app fails to start, extend the length of your signing key to at least 32 characters.
Closes #1022
=> Raise lower limit for JWT signing key from 16 to 32 characters

config/slskd.example.yml, docs/config.md, src/slskd/Core/Options.cs, src/slskd/Users/UserService.cs
Many P2P tools offer support for loading IP range blocklist files, such as those from [i-blocklist](https://www.iblocklist.com/lists). These contain lots of entries, so putting all the CIDRs from one of the lists into the main configuration file quickly becomes unwieldy, and also makes it hard to update the list later.
This PR adds support for loading an external blacklist file, whose entries are merged with any manual entries in the `cidrs` configuration section. Since many blacklist files are quite large (250k+ entries) this PR also introduces a cache for the `IPAddressRange` objects, to prevent having to re-load the file and re-parse every single CIDR string every time a call to `IsBlacklisted` is made. This cache is currently updated at validation time (within the `Validate` …
=> Add support for CIDR blacklist files

src/slskd/Core/Options.cs, src/slskd/Program.cs
Currently the behavior of the environment variable `NO_DISK_LOGGER` is inverted, and it's not possible to disable disk logging via the command line because I made a mistake when originally implementing the `Disk` option.
Correcting this would involve changing the backing property from `Disk` to `NoDisk` to properly reflect the behavior, but that would be a breaking change for anyone that had set the value of the `disk` property in their config.
This PR fixes the problem by disabling disk logging by default, and renaming the environment variable and command line argument to drop the `no`.
Closes #1115
=> Disable disk logging by default

docs/reverse_proxy.md
Fixes the problem I encountered with the reverse proxy setup when I tried out downloading a 5GB file from my slskd setup.
By default Nginx has its own limit of body size of 1MB, and also its own proxy buffering. These two settings disable them.
=> Improve reverse proxy setup for Nginx

src/slskd/Files/FileExtensions.cs, src/slskd/Relay/RelayClient.cs, src/slskd/Shares/SoulseekFileFactory.cs, src/slskd/Transfers/Uploads/UploadService.cs
#320 
`new FileInfo(fileName).Length` reports the filesystem length of a symlink itself, which is a nonsensical value.
If a file happens to be shorter than that value, the download never finishes and client disconnects through a timeout.
If a file happens to be longer than that value, the downloaded file is truncated to the length equal to that value.
This pull requests adds code that resolves the symlink first (if it's a symlink).
I have tested the code on my Linux machine.
=> Handle file symlinks in shares correctly

src/slskd/Application.cs, src/slskd/Files/FileExtensions.cs, src/slskd/Files/FileService.cs, src/slskd/Relay/RelayClient.cs, src/slskd/Relay/RelayService.cs, src/slskd/Shares/ShareScanner.cs, src/slskd/Shares/ShareService.cs, src/slskd/Shares/SoulseekFileFactory.cs, src/slskd/Transfers/Uploads/UploadService.cs
Builds on #1158 by @milleniumbug.
Closes #320 
The logic is encapsulated in the `FileService` class along with the other file I/O, as cross-platform support has been shaky in the past and I don't trust it fully.  Symlink support in .NET is fairly new and I was able to find at least 3 open issues in the dotnet runtime repository related to erroneous results, and I suspect issues will be encountered in the future.
I tested this with both directory (which were working already) and file symlinks, confirming that both browse and search responses return the correct file size, and that downloads of each complete as expected.  I haven't tested with the relay, but there's no reason it should be any different than regular uploads.
Moving forward (and this is more of a note to myself I guess), no …
=> Add support for file symlinks

src/slskd/Application.cs
A cast from 32 bit to 64 bit integers when computing bytes from a configuration value specified in megabytes would result in an overflow for higher values.  This PR converts the operands of that megabyte conversion to 64 bit integers, which yields a 64 bit integer when multiplied with a 32 bit value.
Closes #1174
=> Fix 32 bit integer overflow when computing byte limits

.github/workflows/ci.yml
Closes #1197 
The upload action no longer uploads hidden files by default.  I don't think there are any, but if this blows up that'll be the reason.
=> Bump upload- and download-artifact actions to v4

src/web/src/components/App.jsx
Previously, the theme setting would default to the device preference on each load. So, if a user preferred light theme for slskd despite having a dark device theme, they would need to toggle the theme on each page load. By saving the theme preference in localStorage, we can override the device default with the user's manual preference.
Addresses my main concern in issue #1198.
This is a re-implementaiton of the (abandoned?) PR #1065 but implements the feature using `localStorage` per the suggestion in [the comment on that PR](https://github.com/slskd/slskd/pull/1065#issuecomment-1913637361).
=> Remember theme setting between page loads

.github/workflows/ci.yml
The following actions use a deprecated Node.js version and will be forced to run on node20: 
- actions/checkout@v3
- docker/setup-qemu-action@v2
- docker/setup-buildx-action@v2
- docker/login-action@v2
- docker/build-push-action@v3. 
For more info: https://github.blog/changelog/2024-03-07-github-actions-all-actions-will-run-on-node20-instead-of-node16-by-default/
=> Bump deprecated actions

src/slskd/Common/CommonExtensions.cs
This change was made in #1215 but has the potential to screw everything up, so I'm going to deploy it alone and do some testing in the canary to limit the blast radius.
=> Rssume remote filenames use a backslash, unless forward slashes are present

Dockerfile
.net 6 onwards, DOTNET_ is preferred over COMPlus_ https://github.com/dotnet/runtime/commit/fbdcec9060f46353761ac8ee14d11d6206049395 it first uses DOTNET_, and then COMPlus_ as a legacy fallback.
=> use DOTNET_ var in docker

config/slskd.example.yml, docs/config.md, src/slskd/Common/Validation/EnumAttribute.cs, src/slskd/Core/Options.cs, src/slskd/Events/EventBus.cs, src/slskd/Events/EventsDbContext.cs, src/slskd/Events/Types/EventRecord.cs, src/slskd/Events/Types/Events.cs, src/slskd/Integrations/Scripts/ScriptService.cs, src/slskd/Program.cs
User-defined scripts can be configured to run when application events are raised.  Scripts are given a name (useful for troubleshooting!), a list of triggering events, and a `run` command that's used to execute the script.
The `run` command must be at least one word, with the first word identifying the executable to run and the rest of the string being the command and arguments that will be passed to the executable when the script is run.  The executable needs to be on the system's PATH, otherwise it must be the fully qualified path to the file on disk.
A reserved placeholder value `$DATA` is replaced with the stringified JSON data associated with the event that caused the script to run.  It's the responsibility of the script to parse and handle this JSON.
Here are a few examples:
```yaml …
```
=> Add the ability to run user-defined scripts when application events are raised

docs/config.md
Preivously the config docs for search filters used the same text from share filters (possibly due to a copy and paste mistake?). This PR fixes that and makes clear what the search filters config actually does.
=> Fix search filter config docs

docs/config.md
Follow up to #1224 that tweaks the headings and adds more examples (with an explanation of what they are!)
Thanks again @nhawke
=> Fix a copy/paste mistake in search filter documentation

config/slskd.example.yml, docs/config.md, src/slskd/Common/Validation/ValidateAttribute.cs, src/slskd/Core/API/Controllers/ApplicationController.cs, src/slskd/Core/Constants.cs, src/slskd/Core/Options.cs, src/slskd/Events/API/EventsController.cs, src/slskd/Events/EventBus.cs, src/slskd/Integrations/Pushbullet/PushbulletService.cs, src/slskd/Integrations/Scripts/ScriptService.cs, src/slskd/Integrations/Webhooks/WebhookService.cs, src/slskd/Program.cs
Webhooks (outbound HTTP requests) can be configured to be called when application events are raised.  Webhooks are given a name (useful for troubleshooting!), a list of triggering events, a `call` configuration that defines the HTTP request to be made, and timeout and retry configuration.
Webhook HTTP requests are always a `POST`, and will always include the event data in the body, serialized as JSON.  Users define a fully-qualified endpoint address, an optional collection of headers, and an optional flag to ignore HTTPS errors caused by invalid (e.g. self signed) certificates.
If unconfigured, the default timeout for requests is 5 seconds, and each request will be attempted only once per event.
```yaml
integration:
webhooks:
my_basic_webhook_using_defaults:
on:
- All
call:
url: …
```
=> Add the ability to call HTTP endpoints (webhooks) when application events are raised

docs/config.md
Hi, I think there is a typo in the indentation of this YAML block. Do you agree?
=> docs: fix YAML indentation

src/slskd/Program.cs
Suppresses some behaviors of ASP.NET that make it difficult to pin down API contracts
=> Tweak ASP.NET setup, add metadata to Swagger/OpenAPI

src/slskd/Program.cs
=> Include Content-Type header when returning Prometheus metrics via /metrics

docs/config.md, src/slskd/Events/API/EventsController.cs, src/slskd/Events/Types/Events.cs
Part of the ongoing work to add webhooks and scripts, this PR adds the `RaiseEvent` HTTP endpoint (helpful for testing) and finalizes the documentation.
=> Add an endpoint to allow raising of events (for testing purposes)

src/slskd/Relay/API/Controllers/RelayController.cs
#1229 bumped multipart request limits for the Relay up to 10gb, which I thought to be insanely high prior to seeing a reddit post where someone is attempting to download a 30gb file.
This PR bumps the limit for shares to one tebibyte (terrabyte) and the limit for individual files to 10 tebibytes.
If this project lasts long enough for this to become a problem, I will be amazed.
=> Bump Relay multipart request limits to insanely high values

config/slskd.example.yml, docs/config.md, src/slskd/Core/API/Controllers/SessionController.cs, src/slskd/Core/Options.cs, src/slskd/Program.cs
This PR adds a new `headless` option that, when turned on, prevents the application from serving static web content and forbids login (JWT creation) with username and password.
Most API endpoints remain functional but callers will need to use API key authentication or a JWT created outside of the application and signed with the configured signing key.
The following endpoints (functions) are effectively disabled, as they can only be authenticated with a JWT:
* Application shutdown and restart
* Retrieval of the 'debug' view of configuration (contains secrets)
* Retrieval of the YAML file contents or location on disk
* Update of the YAML file
* Connect and disconnect of the controller when running as a Relay agent
When I configured these to use JWT authentication only, I did so because I …
=> Add 'headless' mode

src/slskd/Application.cs, src/slskd/Search/SearchService.cs
This PR will clean up any Search records that are stuck in a non-terminal state.  This includes single-character searches (will require a separate fix), searches that fail because Soularr is sending them too fast (reported a couple of times on Discord), and searches that are in progress when the application shuts down.
Related to #1263.
=> Clean up dangling Search records on startup

src/slskd/Search/API/Controllers/SearchesController.cs, src/slskd/Search/SearchService.cs, src/web/src/components/Search/Searches.jsx
The existing search logic is such that if any errors are encountered when initializing the search, the search record will get 'stuck' in the initializing state and will appear to be underway to the user.  Among the errors that can cause this are input errors, specifically input of search queries that consist of only a single letter, which are not allowed.
This PR ensures search records are cleaned up in the event of an error.
=> Fix 'stuck' searches, including those that contain a single letter

config/slskd.example.yml, src/slskd/Core/Options.cs, src/slskd/Integrations/Scripts/ScriptService.cs, src/slskd/Program.cs
Closes #1278 
Documentation to follow once folks have had a chance to confirm functionality
=> Refactor user-defined scripts

Dockerfile
Hi 👋🏼 
For the script integrations since the $DATA is in JSON it would be nice to write our custom scripts a bit cleaner and using `jq` would allow for that.
So instead of:
```sh
name=$(echo "$1" | awk -F'"localDirectoryName": "' '{print $2}' | awk -F'",' '{print $1}')
```
we can use:
```sh
name=$(jq -r '.localDirectoryName' <<< "$1")
```
Besides adding a few kilobytes to the image I don't see any harm with including this tool by default?
=> feat(container): Add `jq`

config/slskd.example.yml
The example YAML file incorrectly demonstrates the search retention setting as `searches`, when it's really `search`
=> Fix search retention example

src/web/src/components/Browse/Browse.jsx, src/web/src/components/Rooms/Rooms.css, src/web/src/components/Rooms/Rooms.jsx, src/web/src/components/Users/Users.jsx
This PR adds a context menu for messages in chat rooms. The context menu adds the ability to format a reply, view the user's profile, or browse their shares. The context menu can be accessed by right clicking on a chat message in a room.
Modern UI features are desired by many soulseek users who are hesitant to adopt slskd even if they understand the architectural advantages (see prevalence of hacky nicotine clients on dockerhub). A context menu to make the chat feel more user-friendly could attract users and I have had fun using it thus far.
I am trying to make a feature to ignore users, but it will be a more significant challenge to implement the backend endpoint to add a user to a blacklist. Current solutions for both user and managed blacklists seem improper for this task.
In the Room …
=> Adding context menu to rooms with reply, view user profile, and browse shares

src/slskd/Application.cs, src/slskd/Search/API/Controllers/SearchesController.cs, src/slskd/Search/SearchService.cs, src/slskd/slskd.csproj, src/web/src/components/Search/SearchStatusIcon.jsx
Essentially moves all of the search logic into a try/catch block to attempt to ensure searches are finalized if they don't complete successfully.
Soulseek.NET is bumped to 7.0.0 as well, which incorporates https://github.com/jpdillingham/Soulseek.NET/pull/839.  [This line](https://github.com/jpdillingham/Soulseek.NET/pull/839/files#diff-246696b5b1ce06f8977980e6acb1bfc649c4c9b18f56679fa53476613c77f432L3949) is of particular interest (I think) because it updates the state (and thus fires the `stateChanged` function) in the finally block, which possibly executes after the async `Task` for the search has completed.  This _might_ be playing into the problem.
Related to #1306
=> Refactor search logic to help prevent 'hanging' records

src/slskd/Application.cs, src/slskd/Users/API/Controllers/UsersController.cs, src/slskd/slskd.csproj, src/web/src/components/Search/Response.jsx
Soulseek.NET v7 changed the return type of the underlying method to return multiple directories, and in doing so created a bug.  That bug was fixed with the upgrade to 7.0.3.
Additionally, I never adjusted the related logic in slskd to handle multiple directories.  This PR does that, taking the first directory only.
I _might_ update things later to include subdirectories, but because this only works with Soulseek NS (Qt and Nicotine+ don't send more than 1 directory, nor does slskd) it's not a high priority.
=> Fix bug preventing full directory from being fetched while reviewing search results

src/slskd/Core/Data/Migrations/Z07062025_TransferIndexesMigration.cs, src/slskd/Core/Data/Migrator.cs, src/slskd/Core/Data/SchemaInspector.cs, src/slskd/Transfers/TransfersDbContext.cs
Adds indexes to `TransfersDbContext`, but existing databases aren't affected, so a new migration to add them was needed.
=> Add a few indexes on the Transfers database to improve performance

src/slskd/Application.cs, src/slskd/Core/API/Controllers/ServerController.cs, src/slskd/Core/ConnectionWatchdog.cs, src/slskd/Core/State.cs, src/slskd/Program.cs, src/web/src/components/App.jsx
A user on Discord questioned whether a DNS resolution failure might be breaking reconnect logic, so I went down a rabbit hole and made some changes.
Functional change:
* Changing options while the app is trying to reconnect will attempt reconnect immediately and reset the backoff logic (users no longer have to wait ~5 minutes for the next attempt for changes to server address or port take effect)
* Clicking the network icon on the UI also resets the backoff logic, and when connecting the app using the UI, the connection 'watchdog' is now used, ensuring retries if the initial attempt fails
* Disconnecting via the API now cancels any in-progress reconnect process
* The network icon overlay changes to indicate when a retry attempt is underway (green sync icon), when we're waiting for the …
=> Adjust auto-reconnect logic

src/slskd/Application.cs, src/slskd/Events/API/EventsController.cs, src/slskd/Events/Types/Events.cs
Hey there, apologies for the unsolicited PR—feel free to completely reject this if it's out of scope!
This PR adds three new events for webhooks and scripts: `PrivateMessageReceived`, `PublicChatMessageReceived`, and `RoomMessageReceived`. The format for these looks like this:
```json
{
"type": "PrivateMessageReceived",
"version": 0,
"username": "User",
"message": "Example message",
"blacklisted": false,
"id": "ba0392f7-154a-40d2-bf3e-463fcb3cefaf",
"timestamp": "2025-06-25T21:50:05.3390708Z"
}
{
"type": "RoomMessageReceived",
"version": 0,
"roomName": "ExampleRoom",
"username": "User",
"message": "Example message",
"blacklisted": false,
"id": "6e105322-e16d-4626-ac71-434f0da6b679",
"timestamp": "2025-06-25T22:23:57.5679935Z"
}
```
I made the decision to send chat events *before* the …
=> Add chat events for webhooks and scripts

src/slskd/Application.cs, src/slskd/Common/TimedCounter.cs, src/slskd/Core/Metrics.cs
Prometheus can already figure this out from the search counter.  This is computed locally so we can display it on the UI without computing it from history.
=> Add metric to count search requests per second

src/slskd/Application.cs, src/slskd/Common/CommonExtensions.cs, src/slskd/Core/Options.cs, src/slskd/Program.cs
I noticed this morning that changing the Soulseek diagnostic level from `Info` to `Debug` didn't update the UI or tell me I had to restart.  Digging further I found that the 'diff' that is done between the old and new configuration didn't detect the change, and the underlying cause is that the diff logic ignores enum values (rather, tries to traverse them).
`DiagnosticLevel` is the only option that's backed by an enum, so it is the only one affected.
=> Fix bug preventing proper change detection when updating options with an enum type

src/slskd/Application.cs
Long story short, I discovered the CPU utilization rose substantially for each entry in the list of incoming search request filters, as did garbage collection pressure.  I finally tracked it down to inefficiencies of `IEnumerable` handling; to iterate over one (such as `Any()` in this example) a whole state machine is created, and this can't be optimized out because of the dynamic nature.
I switched the type of collection for the compiled filter regular expressions from `IEnumerable` to `Regex[]` and the computation time for filtering dropped from ~45ms for a list of 30 filters to under 1ms (not sure how many ns but negligible).
Here we see, from left to right:
* 2 search filters
* Distributed network disabled (trying to find the source)
* 15 search filters
* 0 search filters
I'm positive …
=> Substantially improve performance of search request filtering

src/slskd/Application.cs, src/slskd/Events/EventService.cs, src/slskd/Shares/ShareScanner.cs, src/slskd/Shares/ShareService.cs
Following up from #1413 I took a look at all of the stateful service classes and am making various small adjustments to ensure things are stored as read only lists and that they are materialized to memory where needed, instead of potentially allowing lazy enumeration.
=> Ensure lists stored as class property values are read only and properly materialized

docs/config.md
Some of the environment variables in the configuration doc were missing the `SLSKD_` prefix, i.e. `ROOMS` should be `SLSKD_ROOMS`. I encountered this while setting up slskd with Docker Compose, as ROOMS were not auto-joining. I tested all of these changes and they all require the `SLSKD_` prefix in order to function correctly.
I also cleaned up the alignment in a few markdown tables while i was editing the file.
=> fix(docs): add missing prefixes to some environment variables

src/slskd/Core/Data/ConnectionString.cs, src/slskd/Core/Data/ConnectionStringDictionary.cs, src/slskd/Program.cs
I'm working on adding Dapper, which deals with connection strings directly.  Currently the only way to get a connection string is by instantiating an Entity Framework `DbContext`, and that's wasteful and creates further dependency on something I want to remove.
This PR adds `ConnectionStringDictionary`, which is an extremely light, immutable, key-value store of database names and connection strings.  This is injected into the DI container as a singleton and will be available to services downstream.
Also adds a `ConnectionString` class that works like a `string`, just to help avoid confusing the two.
=> Refactor initialization of database connection strings

src/slskd/Core/Data/ConnectionString.cs, src/slskd/Core/Data/Databases.cs, src/slskd/Core/Data/Migrations/Z04012025_TransferStateMigration.cs, src/slskd/Core/Data/Migrations/Z07062025_TransferIndexesMigration.cs, src/slskd/Core/Data/Migrations/Z07262025_PrivateMessageWasReplayedMigration.cs, src/slskd/Core/Data/Migrator.cs, src/slskd/Program.cs
With Dapper on the way code will be dealing with specific databases and connection strings more frequently.  This PR adds a primitive `Database` type to represent database names and adjusts the `ConnectionStringDictionary` so that the key is a `Database`.  This type is deliberately designed without implicit conversions to `string`.
Adjusts the `Migration` logic to pass the connection string dictionary down; migrations no longer need to reference databases by name or build connection strings.
=> Eliminate 'magic strings' when referencing databases and connection strings

src/slskd/Core/API/Controllers/OptionsController.cs
=> Fix bug causing 'Value cannot be null. (Parameter 'instance')' while editing a commented-out config

src/slskd/Common/Validation/FileExistsAttribute.cs
A discord user is having a problem where the https PFX file is randomly being reported as being locked.  This PR explicitly closes the file in the validation logic and uses a different method for disposal, just in case it's holding the file open.
=> Tweak how file access is handled when validating config

src/slskd/Core/Options.cs, src/slskd/Transfers/Uploads/UploadQueue.cs, src/slskd/Transfers/Uploads/UploadService.cs, src/slskd/slskd.csproj
Users with large and/or active shares report various issues with uploads, ranging from a high number of failed transfers, transfers getting "stuck" on the UI, and all uploads to some users halting after some time.
This PR aims to improve (ideally, resolve) these issues by splitting the logic that enqueues (adds to database in queued state) uploads and that actually uploads the files.
I have added additional checks to guard against duplicated records, added additional try/catch logic that aims to properly update database records in the event of failures, and added task continuation logic to do the same.
We'll see if this helps or not.  I have an experimental branch that introduces an "upload scheduler" which will reduce the number of C# `Tasks` from 1 for every enqueued file to just 1 for …
=> Refactor upload logic, splitting file enqueue and upload and adding defensive checks throughout

src/slskd/Transfers/Downloads/DownloadService.cs, src/slskd/Transfers/Uploads/UploadService.cs
There's an ongoing problem on some systems (particularly those using copy-on-write filesystems like ZFS and Btrfs) where transfers get "stuck" in the database with a state that doesn't include the `Completed` flag, which causes all sorts of issues.
There are basically three ways this can happen:
1. A logical error that causes the transfer to exit "uncleanly" and without updating the database with a final status update
2. A race condition among threads that allows a progress update to happen after the final state update
3. A system- or filesystem-level issue that causes SQLite journal entries to arrive out of order, applying an update from a progress event after the final state update, overwriting a completed status with `InProgress`
I've made a bunch of changes in the past (and recently) …
=> Refactor transfer progress update logic
