src/slskd/slskd.csproj
=> Generate documentation file on build

src/slskd/Startup.cs
The option `ENABLE_SWAGGER` now dictates whether swagger components are configured.  It's on by default.
The option `XML_DOC_FILE` can be used to specify the path to the XmlDoc file to provide to swagger.  It defaults to `slskd.xml` in the same directory as the application executable.
If the XmlDoc file isn't found, it isn't supplied when configuring swagger.  This prevents errors (see #2) in request handling.  If swagger is initialized with no XmlDoc, the resulting swagger file will not contain any descriptions of endpoints or parameters.
Closes #2
=> Add options to disable swagger and specify alternate XmlDoc file

.github/configuration/changelog.json, slskd.sln, src/slskd/Controllers/SessionController.cs, src/slskd/Program.cs, src/slskd/Startup.cs
Also adds a couple of categories to the release changelog configuration.
=> Make Swagger and Prometheus opt-in, authentication opt-out

src/slskd/Program.cs, src/slskd/slskd.csproj
Adds `Utility.EnvironmentVariables`, refactors handling, and adds a list of available environment variables to the output of `--help`
=> Simplify handling of environment variables

src/slskd/Common/Configuration/EnvironmentVariables.cs, src/slskd/Common/Validation/FileExistsAttribute.cs, src/slskd/Options.cs, src/slskd/Program.cs
=> Add the ability to specify the config file location

Dockerfile, bin/publish
=> Use TARGETPLATFORM to determine binary target in Dockerfile

src/slskd/slskd.csproj
Also bumps a couple of other packages to the latest.
=> Bump Soulseek.NET to 2.0.4

src/slskd/Common/SharedFileCache.cs, src/slskd/Service.cs
See also https://github.com/jpdillingham/Soulseek.NET/pull/500
=> Normalize path separators to backslash in search, browse, and directory content responses

src/slskd/Common/ISharedFileCache.cs, src/slskd/Common/SharedFileCache.cs, src/slskd/Service.cs
=> Update server with shared file and directory counts

src/slskd/slskd.csproj
Also bumps a few other packages
=> Bump Soulseek.NET to 2.2.0

src/slskd/slskd.csproj
Soulseek.NET to 2.3.3, a few others
=> Bump dependencies

src/slskd/Common/Extensions.cs, src/slskd/Options.cs, src/slskd/Program.cs, src/slskd/Properties/slskd.yml, src/slskd/Service.cs
=> Add SOCKS5 proxy support

Dockerfile
=> Create and map APP and INCOMPLETE dirs in Dockerfile

src/slskd/slskd.csproj
Also bumps other dependencies.
=> Bump Soulseek.NET to 3.0.0-pre-60821754

src/slskd/Application/Messaging/API/DTO/UserDataResponse.cs, src/slskd/Application/Peer/API/DTO/UserDataResponse.cs, src/slskd/slskd.csproj
Also bumps a couple of cross cutting packages
=> Bump Soulseek.NET to 3.0.0-pre-62621233

.github/workflows/ci.yml, Dockerfile
Closes #103 to fix the created label and adds a few more, including revision.  Sets a couple of additional environment variables to pass container metadata through to the application (eventually), and cleans up some unused envars in the CI definition.
=> Dockerfile tweaks

src/slskd/Program.cs
This PR makes it easier to figure out which provider is causing configuration issues.
Closes #83
=> Move configuration dump to before validation

src/web/src/components/Search/Response.js
=> make sure props really changed before rebuilding tree

src/slskd/Application/Service.cs, src/slskd/Options.cs
=> Don't require Soulseek credentials, don't automatically connect if they are missing

src/slskd/Application/ISharedFileCache.cs, src/slskd/Application/Service.cs, src/slskd/Application/SharedFileCache.cs, src/slskd/Common/Configuration/DefaultValueConfigurationSource.cs, src/slskd/Options.cs, src/slskd/Program.cs
=> Allow multiple shared directories

src/slskd/Application/Management/API/Controllers/SessionController.cs, src/slskd/Common/Configuration/DefaultValueConfigurationSource.cs, src/slskd/Options.cs, src/slskd/Startup.cs
=> Tweak some config items for consistency

src/slskd/Startup.cs
=> Fix Swagger UI bug when using a custom UrlBase

README.md
It's good practice to use docker-compose files instead of docker run, please add them to the readme. Thanks!
=> Add docker-compose.yml file to the README.md

src/slskd/Application/Application.cs, src/slskd/Application/SharedFileCache.cs
=> Swap forward slashes with backslashes in browse responses

src/slskd/Application/Application.cs, src/slskd/Application/ISharedFileCache.cs, src/slskd/Application/SharedFileCache.cs
=> Use shared file cache when resolving directory contents

src/slskd/Startup.cs
Because the existing Entity Framework implementation is using SQLite, DbContexts create the backing database files and create the schema the first time they are used, if the file doesn't exist (or is lacking the schema).
The code uses `DbContextFactory` to create instances without regard to this, or concurrency in general, so in cases where a database file doesn't exist, it is possible for two threads to simultaneously try to create the database, resulting in the Exception documented in #161.
This PR adds code to the application `Startup` to create instances of all SQLite databases so that files can be created before they have a chance of being referenced by the application.
There still exists the possibility that a file is deleted while the application is running, in which case it will …
=> Initialize DbContext instances at startup

src/slskd/Application/SharedFileCache.cs
=> Remove logging for every search query

src/slskd/Application/SharedFileCache.cs
=> Return empty browse results while scanning shares

src/web/src/components/App.js, src/web/src/components/Chat/Chat.js, src/web/src/components/Rooms/Rooms.js, src/web/src/components/Search/Search.js, src/web/src/components/Shared/ErrorSegment.js, src/web/src/components/Transfers/Transfers.js, src/web/src/lib/chat.js, src/web/src/lib/rooms.js, src/web/src/lib/search.js, src/web/src/lib/transfers.js
=> Trap and attempt to recover from unexpected API responses in the UI

src/web/src/components/App.js, src/web/src/lib/api.js
=> Fix redirect loop when unauthenticated

src/slskd/Core/API/Hubs/ApplicationHub.cs, src/slskd/Startup.cs
Per the Microsoft docs here: https://docs.microsoft.com/en-us/aspnet/core/signalr/authn-and-authz?view=aspnetcore-5.0
JavaScript clients can then be connected with:
```js
const connection = new signalR.HubConnectionBuilder()
.withUrl('http://localhost:5000/hub/application', { accessTokenFactory: () => 'jwt string here' })
.build();
```
=> Configure SignalR security

src/slskd/Core/API/Hubs/ApplicationHub.cs, src/web/package-lock.json, src/web/package.json, src/web/src/components/App.js, src/web/src/config.js, src/web/src/lib/api.js, src/web/src/lib/chat.js, src/web/src/lib/hubFactory.js, src/web/src/lib/session.js
Presently timers and polling of `/application` were used to determine server state.  This PR leverages the new application SignalR hub to get immediate state updates via websocket.
Closes #203
=> Use SignalR for application state

src/slskd/Common/Extensions.cs
Makes these methods consistent with the built in serializer, and allows `IPAddress` to be serialized.
=> Add serializer options to ToJson and ToObject extension methods

README.md
Fixes #221 
This just bothered me because I kept searching ".yaml" in the file tree and didn't find anything.
Thanks for the project!
=> Update example config file link in README

src/slskd/slskd.csproj
Experimental; re-enables server garbage collection and forces concurrent GC.  Discussion in #251 
I have no idea why I turned server garbage collection off in the first place; it has been like this for 2 years.  It may have been an artifact of something I was seeing with 2.1.
=> Tweak garbage collection settings

config/slskd.example.yml, src/slskd/Application.cs, src/slskd/Options.cs, src/slskd/slskd.csproj, src/web/package-lock.json
This should help force bad child connections to disconnect sooner.
=> Add connection write timeout option

src/slskd/Common/Validation/DirectoryExistsAttributes.cs, src/slskd/Options.cs
=> Verify that downloads and incomplete directories are writeable when configuration changes

src/slskd/Transfers/API/Controllers/TransfersController.cs, src/slskd/slskd.csproj, src/web/package-lock.json, src/web/src/components/Browse/Directory.js, src/web/src/components/Search/Response.js, src/web/src/lib/transfers.js
This should improve connectivity and performance when downloading files from search results.
=> Download files in batches, prime connections before the first enqueue

src/slskd/Application.cs, src/slskd/Core/API/Controllers/ApplicationController.cs, src/slskd/Search/SearchService.cs
=> Manually collect garbage after each search

src/slskd/Shares/SharedFileCache.cs, src/slskd/State.cs
=> Respond to search, browse, and directory contents requests appropriately while the cache is unfilled

docs/config.md, src/slskd/Application.cs, src/slskd/Core/API/Controllers/OptionsController.cs, src/slskd/Program.cs, src/slskd/Startup.cs, src/web/src/components/System/Options/Edit.js
=> Allow the path to the configuration file to be specified

src/slskd/Program.cs
=> Fix bug preventing some command line arguments from being populated

src/slskd/Options.cs, src/slskd/Program.cs, src/slskd/Search/API/Hubs/SearchHub.cs, src/slskd/slskd.csproj
=> Fix bug causing configuration location to be ignored

src/web/package.json, src/web/src/components/Browse/Browse.js
=> Compress localStorage strings

src/slskd/Transfers/API/Controllers/TransfersController.cs, src/web/package-lock.json
This will help provide some insight into #318
=> Verbosely log download attempts

src/slskd/Application.cs, src/slskd/slskd.csproj
Also logs failed and denied downloads
=> Bump Soulseek.NET to 4.1.0

src/slskd/Transfers/API/Controllers/TransfersController.cs
=> Don't invalidate cache when priming connections

src/web/src/lib/api.js
=> Pass-through authentication to API calls from UI by default

src/slskd/Common/TokenBucket.cs, src/slskd/Transfers/API/Controllers/TransfersController.cs, src/slskd/slskd.csproj
Also bumps Soulseek.NET to 4.4.5
=> Fix bugs with download speed governance and queue behavior

config/slskd.example.yml, docs/config.md, src/slskd/Options.cs, src/slskd/Users/UserService.cs, tests/slskd.Tests.Unit/Transfers/Uploads/UploadQueueTests.cs
=> Identify leechers

src/slskd/Application.cs, src/slskd/Users/UserService.cs, src/slskd/slskd.csproj
=> Ensure transfers in progress continue if the client is disconnected from the server

src/web/package-lock.json
=> Generate new lockfile

src/web/src/components/Transfers/TransferGroup.js, src/web/src/components/Transfers/TransferList.js
=> Update UI to display newer queued states

src/slskd/Application.cs, src/slskd/Common/Logging/LogRecord.cs, src/slskd/Program.cs, src/slskd/State.cs, src/slskd/slskd.csproj
=> Log distributed messages as debug, add distributed state

src/web/src/components/App.css, src/web/src/components/Shared/FileList.js, src/web/src/lib/util.js
=> Improve file attribute display; show VBR flag, lossless depth/sample rate

docs/config.md, src/slskd/Options.cs
Also adds documentation for description option
=> Don't require a restart when changing description

config/slskd.example.yml, docs/config.md, slskd.sln, src/slskd/Options.cs, src/slskd/Program.cs
=> Add an option to disable HTTPS

src/slskd/Options.cs, src/slskd/Shares/SharedFileCache.cs
Closes #461 
Also makes share logging easier to read, and fixed erroneous reporting of exclusions as shares.
=> Account for exclusions when validating shares

src/slskd/Search/API/Controllers/SearchesController.cs, src/slskd/Search/SearchDbContext.cs, src/slskd/Search/SearchService.cs, src/web/package-lock.json, src/web/package.json, src/web/src/components/App.js, src/web/src/components/Search/Searches.js
Also prevents searches from being saved to the database if there's a validation issue (creating the search throws)
Closes #468
=> Force database timestamps to use UTC, trap search errors and display toast

.github/workflows/ci.yml
=> Add additional OS/architecture combinations

.github/workflows/ci.yml
=> Mark binaries as executable

src/slskd/Shares/SoulseekFileFactory.cs
=> Log failed metadata reads at debug level

config/slskd.example.yml, docs/config.md, src/slskd/Application.cs, src/slskd/Options.cs
=> Allow distributed network logging to be disabled (and disable it by default)

src/web/package-lock.json, src/web/package.json, src/web/src/components/Shared/CodeEditor.js
A recent change to the lockfile bumped a version somewhere that broke something in the dependencies of CodeEditor.  This PR fixes it.
=> Fix broken CodeEditor component

src/web/src/components/Search/Searches.js
=> Fix bug preventing Search Again button from working

src/web/src/lib/util.js
I've fixed up the formatSeconds to test if it's longer than an hour then show the extra portion.
=> Tracks that last longer than an hour don't show that.

src/slskd/Shares/SharedFileCache.cs
This wasn't very intuitive, but there's an overload for `GetDirectories` that accepts an instance of `EnumerationOptions`.  This class allows options to be set for skipping system and hidden directories, and ignoring 'access denied' errors.  I've applied both options to both the initial directory enumeration and the subsequent file scans.
Closes #512
=> Fix bug causing a share scan to fail if one of the subdirectories within can't be accessed

config/slskd.example.yml
=> Added rooms to slskd.example.yml

src/slskd/Messaging/API/Controllers/RoomsController.cs, src/slskd/Messaging/RoomService.cs
=> Properly add rooms to tracker after joining

src/slskd/Application.cs, src/slskd/Transfers/Uploads/UploadQueue.cs
=> Accurately forecast queue position for both round-robin and FIFO type queues

src/slskd/Common/RateLimiter.cs
=> Tweak RateLimiter to allow consumers to stop it without flushing

Dockerfile
Trying to keep memory usage down.  Related to #553
=> Set DOTNET_GCConserveMemory in Dockerfile

src/slskd/slskd.csproj
Closes #567 via [Soulseek.NET #744](https://github.com/jpdillingham/Soulseek.NET/pull/744)
=> Bump dependencies, including Soulseek.NET to 5.1.0

config/slskd.example.yml, docs/config.md, src/slskd/Application.cs, src/slskd/Core/Options.cs, src/slskd/Program.cs
=> Consolidate option "flags"

src/web/src/lib/chat.js, src/web/src/lib/shares.js, src/web/src/lib/transfers.js
=> Fix bug with unescaped values in some API calls

src/slskd/Application.cs, src/slskd/Transfers/Uploads/UploadQueue.cs
=> Return slots and queue information in UserInfoResolver

src/slskd/Application.cs
Thanks for the nudge @mathiascode
=> Fix hasFreeUploadSlot

src/slskd/Application.cs, src/slskd/Transfers/Uploads/IUploadService.cs, src/slskd/Transfers/Uploads/UploadService.cs
Closes #583 
Also fixes a bug in the new transfer persistence logic that was preventing existing transfers from being properly identified.
=> Fix several bugs related to uploads

src/slskd/Application.cs
=> Drop incoming search requests that only include excluded terms

config/slskd.example.yml, docs/config.md, src/slskd/Common/RateLimiter.cs, src/slskd/Core/Options.cs, src/slskd/Transfers/Downloads/DownloadService.cs, src/slskd/Transfers/Uploads/UploadService.cs
Related to #598 
Adds a new `experimental` flag that I can use to toggle one-off features for troubleshooting
=> Attempt to make transfer records even more deterministic

src/slskd/Application.cs, src/slskd/Core/Options.cs, src/slskd/Transfers/API/Controllers/TransfersController.cs, src/slskd/Transfers/Downloads/DownloadService.cs, src/slskd/Transfers/Downloads/IDownloadService.cs, src/slskd/Transfers/Uploads/IUploadService.cs, src/slskd/Transfers/Uploads/UploadService.cs
=> Remove SQLite asynchrony

src/slskd/Application.cs, src/slskd/Program.cs
Also fixes a logical ordering issue with share scan state updates.
=> Include Exception when formatting logs

src/slskd/Core/Metrics.cs, src/slskd/Program.cs, src/slskd/Shares/SharedFileCache.cs
This is an experimental change that will only go out to the canary release.
=> Store shared file cache on disk instead of memory

src/slskd/Transfers/Downloads/DownloadService.cs, src/slskd/Transfers/Uploads/UploadService.cs
=> Fix transfer cancellation bug

config/slskd.example.yml, docs/config.md
Includes updates to documentation that should have been included in #641
=> Update documentation to reflect changes to share configuration

src/slskd/Transfers/Downloads/DownloadService.cs
Related to #407 
Does not include opt-out option.
=> Add logic for duplicate filenames

src/slskd/slskd.csproj
=> Remove SonarAnalyzer

src/slskd/Network/NetworkClient.cs
Using the same `HttpClient` instance for all uploads causes them to block.  I knew this but somehow overlooked it.  This PR also sets the timeout to the maximum allowable time; apparently calls are subject to timeout even if they are actively transferring data.
=> Agent upload improvements

config/slskd.example.yml, src/slskd/Common/Cryptography/Pbkdf2.cs, src/slskd/Common/Exceptions/ShareValidationException.cs, src/slskd/Common/Redactor.cs, src/slskd/Common/Validation/UrlAttribute.cs, src/slskd/Core/Options.cs, src/slskd/Network/API/Controllers/NetworkController.cs, src/slskd/Network/API/Hubs/NetworkHub.cs, src/slskd/Network/NetworkClient.cs, src/slskd/Network/NetworkService.cs, src/slskd/Transfers/Uploads/UploadService.cs
Makes a number of improvements to the Network functionality.
=> More Network improvements

src/slskd/Program.cs
This package was clearly not designed to be used with esoteric authentication mechanisms
=> Tweak SignalR auth again

.github/workflows/ci.yml
=> Only build a linux-amd64 Docker container image for canary releases

src/slskd/Shares/IShareRepository.cs, src/slskd/Shares/ShareScanner.cs, src/slskd/Shares/ShareService.cs, src/slskd/Shares/SqliteShareRepository.cs
=> Rebuild filename index after share scan is complete

src/slskd/Application.cs, src/slskd/Core/State.cs, src/slskd/Shares/ShareService.cs
=> Rebuild browse response cache if hosts change

docs/config.md
Document functionality added in https://github.com/slskd/slskd/issues/330
Feel free to ignore this PR if it doesn't match the format of the existing docs.
=> Add blacklist info

src/slskd/Core/API/Controllers/ServerController.cs, src/slskd/Messaging/API/Controllers/ConversationsController.cs, src/slskd/Messaging/API/Controllers/PublicChatController.cs, src/slskd/Messaging/API/Controllers/RoomsController.cs, src/slskd/Search/API/Controllers/SearchesController.cs, src/slskd/Transfers/API/Controllers/TransfersController.cs, src/slskd/Users/API/Controllers/UsersController.cs
=> Forbid server API calls in Agent mode

src/slskd/Shares/IShareRepository.cs, src/slskd/Shares/ShareScanner.cs, src/slskd/Shares/SqliteShareRepository.cs
=> Run database vacuum after scanning and after backing up

src/slskd/Shares/ShareService.cs, src/slskd/Shares/Types/Share.cs, src/web/src/components/System/Shares/ShareTable.js, src/web/src/components/System/Shares/index.js
=> Update the shares UI when config changes, or after scanning

.github/workflows/ci.yml, Dockerfile, src/slskd/slskd.csproj, tests/slskd.Tests.Integration/slskd.Tests.Integration.csproj, tests/slskd.Tests.Unit/slskd.Tests.Unit.csproj
=> Upgrade to .NET 7

src/slskd/Core/Options.cs, src/slskd/Shares/ShareService.cs, src/slskd/Transfers/Uploads/UploadService.cs
=> Replace hard-coded local hostname with Program.LocalHostName

src/slskd/Search/SearchService.cs
Closes #795 
The root cause appears to have been the placement of `SaveChanges()`
=> Fix bug updating search database

README.md
=> Update GitHub badge

src/slskd/Integrations/FTP/FTPClientFactory.cs, src/slskd/Integrations/FTP/FTPService.cs, src/slskd/Integrations/FTP/IFTPClientFactory.cs, src/slskd/slskd.csproj
=> Upgrade FluentFTP to > v40

config/slskd.example.yml, src/slskd/Common/Authentication/AuthPolicy.cs, src/slskd/Program.cs, src/slskd/Relay/API/Controllers/RelayController.cs
=> Add ApiKeyOnly auth policy and use it for Relay endpoints

src/slskd/Common/Compute.cs, src/slskd/Program.cs
Also tweaks certificate generation to make the code easier to follow.
Closes #636
=> Refactor single-instance mutex to use a more specific handle

src/slskd/Core/Options.cs, src/slskd/Relay/API/Controllers/RelayController.cs, src/slskd/Relay/API/Hubs/RelayHub.cs
=> Add CIDR filtering for Relay Agents

src/slskd/Common/Authentication/ApiKeyAuthentication.cs, src/slskd/Common/Authentication/AuthPolicy.cs, src/slskd/Program.cs, src/slskd/Relay/API/Controllers/RelayController.cs, src/slskd/Relay/RelayClient.cs, src/slskd/Relay/RelayService.cs, src/slskd/Shares/ShareService.cs, src/slskd/Transfers/Uploads/UploadService.cs
I ran into some issues while creating the docs for the Relay feature; this PR should clear those up.
=> Miscellaneous Relay refactoring and bugfixes

config/slskd.example.yml, docs/README.md, docs/docker.md, docs/known_issues.md, docs/relay.md, docs/reverse_proxy.md, docs/system_requirements.md
Also adds a `README` to the root of the `docs` directory to serve as a TOC
=> Add documentation for the Relay feature

src/slskd/Relay/RelayClient.cs, src/slskd/Relay/RelayService.cs
=> Adjust a few Relay logs

src/slskd/Common/CommonExtensions.cs, src/slskd/Relay/RelayClient.cs
This should ensure that shares are properly uploaded following every login
=> Improve Relay agent reconnect logic

.github/workflows/ci.yml
=> Update several actions to versions that use node 16

.github/workflows/ci.yml
https://github.com/slskd/slskd/actions/runs/3907644391
=> Update a couple actions that were missed

src/slskd/Relay/API/Controllers/RelayController.cs, src/slskd/Relay/API/Hubs/RelayHub.cs, src/slskd/Relay/IRelayClient.cs, src/slskd/Relay/NullRelayClient.cs, src/slskd/Relay/RelayClient.cs, src/slskd/Relay/RelayService.cs, src/slskd/Relay/Types/Agent.cs, src/slskd/Relay/Types/RelayClientState.cs, src/slskd/Relay/Types/RelayMode.cs, src/slskd/Transfers/Downloads/DownloadService.cs
=> Relay cleanup and polish

bin/build, bin/publish, src/slskd/Program.cs
=> Fix version check (again)

src/web/src/components/App.js
=> Fix routing bug preventing system page from loading

src/web/src/components/App.js
The reload issue was fixed by #857 but it caused #867 and #869.  It's too early in the morning for me to deal with regular expressions so I'm reverting the change until I have had a chance to look at it more closely.
Reopens #555
=> Revert back to catch-all route

src/web/src/components/App.js
=> Wrap each set of routes in a Switch

README.md, docs/docker.md
=> Improve setup docs

.github/workflows/ci.yml
=> Fix versioning in docker

src/web/src/components/Browse/Browse.js
It looks like there's a couple of issues with the current implementation which shows in Performance tab in Chrome:
1) getChildDirectories and in particular the split function. When you look at the code we're doing 3 filters on a reduced array each time, but always starting with the full list of directories. So for every child directory we iterate once over the entire array of all directories to remove 1 item, then for n-1 items we split them, then we find the ones who start with the parent path name. This is very inefficient.
To fix this I added one first iteration that will split the names on them all once and use that depth as a key into a Map and store an Array of the items at that depth. We could possibly go one step further and iterate the array store the d.name split on the last …
=> Trying to speed up the performance of the Browse tab.

config/slskd.example.yml, src/slskd/Common/Exceptions/ForbiddenException.cs, src/slskd/Common/Exceptions/InvalidDirectoryException.cs, src/slskd/Core/Options.cs, src/slskd/Files/API/FilesController.cs, src/slskd/Files/FileService.cs, src/slskd/Files/IFileService.cs, src/slskd/Files/Types/FilesystemDirectory.cs, src/slskd/Files/Types/FilesystemFile.cs, src/slskd/Program.cs, src/slskd/slskd.csproj
This PR lays the groundwork for UI functionality that will allow users to see what's in their downloaded and incomplete folders, and delete the contents.
Related to #205
=> Add API endpoints for listing and deleting downloaded and incomplete files

src/web/src/components/Search/Searches.js
=> Fix occasional blank screen with console message "TypeError: Cannot read properties of undefined (reading 'isConnected')"

src/web/src/components/App.css, src/web/src/components/Search/List/SearchList.js, src/web/src/components/Search/Search.css
This PR aims only to make the mobile layout more usable. Specifically, it fixes overflow issues with the searches page, and makes the menu sticky/scrollable.
=> improve mobile layout

src/web/src/components/Search/Response.js
=> Preserve file selection when fetching directory contents

Dockerfile
Updating some dependencies here, and thank you for this amazing app. I've been using soulseek on my mac with nicotine for years but this makes it so I can just run it on my server instead <3
=> fix: use alpine 3.18 and debian bookworm in docker build

docs/docker.md
👋
This PR just fixes the yaml examples in the docker documentation for the shares.
I came through this while setting up the image.
=> Fixes docker.md yml shares

config/slskd.example.yml, src/slskd/Application.cs, src/slskd/Core/Options.cs
Closes #531 
Here's a little checklist for myself since I keep revisiting this wondering why I haven't merged it.  I haven't tested this yet, and need to confirm that:
=> Add the ability to blacklist by IP address (CIDR)

docs/config.md
#981 added the ability to blacklist by IP address/CIDR; this PR updates the documentation.
=> Add docs for blacklist CIDRs

config/slskd.example.yml, docs/config.md, src/slskd/Core/Options.cs, src/slskd/Program.cs
=> Add an option to disable logging to disk

docs/config.md
=> Add example YAML for cache workers

docs/config.md
=> Add documentation for auto-join feature

src/web/public/robots.txt
=> Add robots.txt

src/slskd/Core/Options.cs, src/slskd/Program.cs
=> FIX: Ensure JWT signing key is at least 32 characters (256 bits)

src/slskd/Program.cs, src/slskd/slskd.csproj
=> Disable append of source revision in version, prevent PrintLogo from throwing for any reason

src/slskd/Application.cs, src/slskd/Core/Clock.cs
Also adds `ClockEventArgs` so that handlers can tell whether an invocation is part of the startup (via `FirstRun`)
This PR moves the start of the clock from one of the very first actions when the application startup sequence starts, to one of the last.  I can't remember why it was where it was, but it needs to be placed after shares have been initialized to support the work I'm doing in #900.
Here's hoping it doesn't need to be moved back for some reason!
=> Delay start of the application's internal clock

config/slskd.example.yml, docs/config.md, src/slskd/Application.cs, src/slskd/Core/Options.cs, src/slskd/Shares/IShareRepository.cs, src/slskd/Shares/IShareService.cs, src/slskd/Shares/ShareService.cs, src/slskd/Shares/SqliteShareRepository.cs
=> Add a setting to re-scan shares on a regular interval (add retention limit to the cache)

.github/workflows/ci.yml, Dockerfile, docs/build.md, src/slskd/Common/Authentication/ApiKeyAuthentication.cs, src/slskd/Common/Authentication/PassthroughAuthentication.cs, src/slskd/Common/Exceptions/ApplicationShutdownException.cs, src/slskd/Common/Exceptions/GitHubException.cs, src/slskd/Common/Exceptions/IntentionalDisconnectException.cs, src/slskd/Common/Exceptions/NotFoundException.cs, src/slskd/Common/Exceptions/OutOfRangeException.cs, src/slskd/Common/Exceptions/RelayException.cs, src/slskd/Common/Exceptions/RetryException.cs, src/slskd/Common/Exceptions/ShareInitializationException.cs, src/slskd/Common/Exceptions/ShareScanInProgressException.cs, src/slskd/Common/Exceptions/ShareValidationException.cs, src/slskd/Common/Exceptions/SlskdException.cs, src/slskd/Common/Exceptions/UnauthorizedException.cs, src/slskd/Transfers/API/Controllers/TransfersController.cs, src/slskd/Transfers/Uploads/UploadService.cs, src/slskd/slskd.csproj, tests/slskd.Tests.Integration/slskd.Tests.Integration.csproj, tests/slskd.Tests.Unit/slskd.Tests.Unit.csproj
=> Upgrade to .NET 8

.github/workflows/ci.yml
=> Drop win-arm build target

src/slskd/slskd.csproj
=> Bump prometheus-net.SystemMetrics to 3.1.0

src/slskd/Application.cs
Currently the application will send search results to users with blacklisted IP addresses because the search response resolver delegate can't pass an IP address reliably (see https://github.com/jpdillingham/Soulseek.NET/issues/789).
I realized that because we cache user endpoints and because we need to fetch the endpoint prior to sending the results, I could get away with fetching the endpoint in slskd and Soulseek.NET would get a cache hit, avoiding the double-fetch that I was previously trying to avoid.
This PR adds logic to fetch the requesting user's IP address and check to see if it's blacklisted prior to sending search results.
I also removed the logging when a blacklisted user made a search request, and instead of sending an empty `SearchResponse` we now return `null` if a user is …
=> Check if user's IP is blacklisted prior to sending search results

src/slskd/Transfers/Downloads/DownloadService.cs, src/slskd/Transfers/Uploads/UploadService.cs
This code was used at one time to try and diagnose issues with database interactions, and is no longer needed.
=> Remove deprecated experimental code

src/slskd/Core/Options.cs
=> Fix crash when setting blacklist CIDRs

config/slskd.example.yml, docs/config.md, src/slskd/Application.cs, src/slskd/Core/Options.cs
=> Add global limits, add limits to configuration documentation

src/slskd/Application.cs
=> Avoid logging searches with server exclusions applied

src/slskd/Common/Validation/FileExistsAttribute.cs
This attribute was added to allow configuration validation to ensure that files specified in the configuration actually exist on disk.  This PR extends the attribute to allow files to be tested for a specified `FileMode` as well, ensuring that files not only exist, but that they can be read/written.
=> Add FileAccess to FileExists attribute, test files for access

src/slskd/Application.cs, src/slskd/Core/ConnectionWatchdog.cs
Starting with wifi disabled, and then enabling:
```
[slskd.Application] [19:01:29 INF] Attempting to connect to the Soulseek server...
[slskd.Application] [19:01:29 ERR] Failed to reconnect: Failed to resolve address 'vps.slsknet.org': No such host is known.
[slskd.Application] [19:01:29 INF] Waiting about a second before attempting to reconnect
[slskd.Application] [19:01:30 INF] Attempting to reconnect to the Soulseek server (#1)...
[slskd.Application] [19:01:30 ERR] Failed to reconnect: Failed to resolve address 'vps.slsknet.org': No such host is known.
[slskd.Application] [19:01:30 INF] Waiting about 2 seconds before attempting to reconnect
[slskd.Application] [19:01:31 INF] Attempting to reconnect to the Soulseek server (#2)...
[slskd.Application] [19:01:31 ERR] Failed to reconnect: …
```
=> Add retry loop to initial server connection (fixes crash when starting the application while the Soulseek server is unreachable)

src/web/src/lib/util.js
=> Fix Non-media files display "Invalid Date'

src/web/src/components/System/Shares/index.jsx
fixes #1167 , 
also can we pls work a bit on dev docs :face_holding_back_tears:
=> fix(web:system:shares): add `theme` to function args

docs/config.md, src/slskd/Application.cs
=> Ignore private and public messages from blacklisted users

src/slskd/Application.cs, src/slskd/Messaging/RoomService.cs
=> Properly ignore room messages from blacklisted users

src/web/package-lock.json
Eliminates the nag message about updating these things.
=> Bump caniuse-lite and browserslist

src/slskd/Relay/API/Controllers/RelayController.cs
=> Set request limit for share upload to 10gb

bin/lint, src/slskd/Events/Types/Events.cs, src/slskd/Messaging/API/Controllers/RoomsController.cs, src/slskd/Properties/analysis.ruleset, src/slskd/Shares/Types/Share.cs, src/slskd/Transfers/Uploads/UploadService.cs, src/slskd/slskd.csproj, tests/slskd.Tests.Unit/Common/Extensions/ToLocalRelativeFilenameTests.cs, tests/slskd.Tests.Unit/Transfers/Uploads/UploadQueueTests.cs, tests/slskd.Tests.Unit/Users/UserServiceTests.cs
Also adds a new script, `./bin/lint` that executes `dotnet format`
=> Resolve some build warnings, run linting and fix a bunch of whitespace

src/slskd/Application.cs, src/slskd/Users/UserService.cs
Closes #970 
Also fixes a misleading Debug log related to blacklist configuration.
=> Log search logs at the 'Debug' level

docs/config.md
I said I'd do this in #1083 and never got to it.
=> Add missing listen_ip_address example

src/slskd/Events/API/EventsController.cs, src/slskd/Events/Types/Events.cs, src/slskd/Transfers/Uploads/UploadService.cs
This PR adds and implements an event, UploadFileCompleteEvent, similar to DownloadFileCompleteEvent.
- Adds EventBus to UploadService
- Creates UploadFileCompleteEvent type
- Raises a UploadFileCompleteEvent on upload completion
=> Added UploadFileCompleteEvent

config/slskd.example.yml, src/slskd/Core/Options.cs, src/slskd/Transfers/Uploads/UploadService.cs
=> Add OptimisticRelayFileInfo flag to (potentially) speed up enqueue of files hosted on a Relay agent

docs/config.md
Assuming the example config and the note a few lines above this change are correct, this should be updated
=> Fix log retention to be days in docs

src/slskd/Users/API/Controllers/UsersController.cs, src/web/src/components/Search/Response.jsx
=> Fix cryptic message if a remote client doesn't return any files when directory contents are requested

src/slskd/Application.cs, src/slskd/slskd.csproj
Release notes [here](https://github.com/jpdillingham/Soulseek.NET/releases/tag/7.1.0)
=> Bump Soulseek.NET to 7.1.0

docs/config.md, src/slskd/Integrations/Scripts/ScriptService.cs, src/slskd/Integrations/Webhooks/WebhookService.cs
Also moves JSON configuration for scripts and webhooks into their respective services to guard against regressions should the shared config change for some reason.
=> Update documentation for scripts

src/slskd/Search/SearchService.cs
=> Refactor handling of searches, attempt to trap un-Completed condition and correct it

src/slskd/Search/SearchService.cs, src/slskd/slskd.csproj
In testing I also noticed a couple of logs that were broken
=> Bump Soulseek.NET to 8.0.0

config/slskd.example.yml, docs/config.md, src/slskd/Core/Options.cs, src/slskd/Program.cs
Closes #1452
I decided to work on this myself, as it was quite easy to implement. This hasn't been thoroughly tested, however it's currently running on my machine as described in the original issue!
=> Support the ability for the web interface to listen on a unix socket

config/slskd.example.yml, docs/config.md, src/slskd/Common/Validation/AbsoluteFilePathAttribute.cs, src/slskd/Common/Validation/FileDoesNotExistAttribute.cs, src/slskd/Core/Options.cs, src/slskd/Program.cs
Expanding on #1453, this PR just moves some things around and adds validation for the option.
=> Refine support for unix domain sockets (UDS)

src/slskd/Transfers/Downloads/DownloadService.cs, src/slskd/Transfers/Uploads/UploadService.cs
Applies the refactoring done to uploads in #1457 to downloads as well
=> Refactor download logic to split enqueue and download
